import Link from "next/link";
import {footballData} from "@/lib/football-data";
import {footballSummary,footballTable} from "@/lib/football";
import {ClubMark,FootballScore,FootballMatchRow,FootballMediaCard,FCEmpty,FCMetrics} from "@/components/FootballUI";
import {FCAction} from "@/components/FootballForms";
export const metadata={title:"EA FC 27"};
export default async function Page(){
 const data=await footballData(),{profile:p,universe:u,season,matches,media,interviews}=data,en=u.language==="en",current=matches.filter(m=>m.season_id===p.current_season_id),summary=footballSummary(current),own=current.filter(m=>m.tracked_club===p.club_name&&[m.home_club,m.away_club].includes(p.club_name)),next=own.find(m=>m.status==="scheduled"&&m.match_date>=u.universe_date),last=own.filter(m=>m.status==="completed").at(-1),table=footballTable(current,season.clubs||[],season.league),place=table.findIndex(t=>t.name===p.club_name)+1,question=interviews.find(i=>!i.answer);
 return <div className="footballWorld" style={{"--club":p.club_color} as React.CSSProperties}>
 <div className="fcHomeTop"><section className="fcIdentity"><div className="eyebrow">EA FC 27 / {p.mode==="manager"?(en?"THE MANAGER":"DER TRAINER"):(en?"THE PLAYER":"DER SPIELER")} / {season.name}</div><h1>{p.person_name}</h1><div className="fcClubLine"><ClubMark name={p.club_name} color={p.club_color} code={p.club_code}/><div><strong>{p.club_name}</strong><span>{p.league} · {p.mode==="manager"?p.formation:`${p.position} · OVR ${p.overall}`} · {u.universe_date}</span></div></div><p className="fcIdentityNote">{en?"The next chapter starts at kickoff.":"Das nächste Kapitel beginnt mit dem Anpfiff."}</p><div className="buttonRow"><Link className="button" href={next?`/fc/match/${next.id}#entry`:"/fc/matches?new=1#entry"}>{en?"Enter match":"Spiel eintragen"} +</Link><Link className="textLink" href="/universes">{en?"Change career":"Karriere wechseln"} ↗</Link></div></section><aside>{next||last?<FootballScore match={(next||last)!} compact en={en}/>:<FCEmpty en={en} href="/fc/matches?new=1#entry">{en?"Add your first fixture. Your career journal starts here.":"Lege deine erste Partie an. Hier beginnt deine Karrierechronik."}</FCEmpty>}</aside></div>
 <FCMetrics items={p.mode==="player"?[{label:en?"APPEARANCES":"EINSÄTZE",value:summary.appearances},{label:en?"GOALS":"TORE",value:summary.goals},{label:"ASSISTS",value:summary.assists},{label:"MATCHRATING",value:summary.rating?.toFixed(1)||"—"},{label:en?"TEAM WINS":"TEAMSIEGE",value:summary.wins},{label:en?"POSITION*":"PLATZ*",value:place||"—"}]:[{label:en?"MATCHES":"SPIELE",value:summary.matches},{label:en?"WINS":"SIEGE",value:summary.wins},{label:en?"DRAWS":"REMIS",value:summary.draws},{label:en?"GOALS":"TORE",value:`${summary.goalsFor}:${summary.goalsAgainst}`},{label:en?"CLEAN SHEETS":"ZU NULL",value:summary.cleanSheets},{label:en?"POSITION*":"PLATZ*",value:place||"—"}]}/>
 <p className="fcTableNote">{en?"*Position is based on recorded league results. Complete the other fixtures to reproduce your in-game table.":"*Der Tabellenplatz basiert auf erfassten Ligaergebnissen. Ergänze die übrigen Partien, um deine Tabelle aus dem Spiel abzubilden."}</p>
 {question&&<section className="fcPressPrompt"><span className="eyebrow">{en?"THE PRESS ROOM":"DER PRESSERAUM"}</span><h2>{question.question}</h2><div className="buttonRow">{question.options.map((a:string)=><FCAction key={a} en={en} action="interview" body={{id:question.id,answer:a}}>{a}</FCAction>)}</div></section>}
 <div className="fcEditorialGrid"><section><div className="sectionHead"><h2>{en?"Around your football":"Rund um deinen Fußball"}</h2><Link href="/fc/media">{en?"All reports":"Alle Berichte"} →</Link></div>{media.length?media.slice(0,5).map(post=><FootballMediaCard key={post.id} post={post} en={en}/>):<FCEmpty en={en}>{en?"Save a match to start your coverage. Reports, fan voices and a press question follow.":"Speichere ein Spiel, um deine Berichterstattung zu starten. Spielbericht, Fanstimmen und Pressefrage folgen."}</FCEmpty>}</section><aside><div className="sectionHead"><h2>{en?"Form & fixtures":"Form & Spielplan"}</h2><Link href="/fc/matches">→</Link></div><div className="fcFormRun">{own.filter(m=>m.status==="completed").slice(-5).map(m=><FootballMatchRow key={m.id} match={m} en={en}/>)}</div><Link className="fcRailLink" href="/fc/career"><span>{en?"THE CAREER FILE":"DIE KARRIEREAKTE"}</span><strong>{p.mode==="player"?`${summary.hatTricks} ${en?"hat-tricks":"Dreierpacks"}`:`${summary.wins} ${en?"wins":"Siege"}`}</strong><span>{en?"Records, seasons, your story":"Rekorde, Saisons, deine Geschichte"} ↗</span></Link><Link className="fcRailLink" href={p.mode==="manager"?"/fc/squad":"/fc/transfers"}><span>{p.mode==="manager"?(en?"THE DRESSING ROOM":"DIE KABINE"):(en?"THE NEXT MOVE":"DER NÄCHSTE SCHRITT")}</span><strong>{p.mode==="manager"?p.formation:(en?"Your next club.":"Dein nächster Verein.")}</strong><span>{p.mode==="manager"?(en?"Squad & tactics":"Kader & Taktik"):(en?"Transfers & contracts":"Transfers & Verträge")} ↗</span></Link></aside></div>
 </div>;
}
