import {NextResponse} from "next/server";import {requireAdmin,apiStatus} from "@/lib/auth";
export async function GET(){try{const {career,universe,client}=await requireAdmin();const out:any={exported_at:new Date().toISOString(),schema_version:"2.0",universe,career};const [{data:teams},{data:seasons},{data:games},{data:universeGames},{data:world},{data:stints},{data:stats},{data:notables},{data:injuries},{data:events},{data:arcs},{data:interest},{data:offers},{data:media},{data:awards},{data:milestones},{data:relationships}]=await Promise.all([
client.from("teams").select("*"),client.from("seasons").select("*"),client.from("games").select("*").eq("season_id",universe.current_season_id),
client.from("universe_games").select("*").eq("universe_id",universe.id),client.from("world_settings").select("*").eq("career_id",career.id),
client.from("team_stints").select("*").eq("career_id",career.id),client.from("player_game_stats").select("*").eq("career_id",career.id),
client.from("game_notables").select("*").eq("career_id",career.id),client.from("injuries").select("*").eq("career_id",career.id),
client.from("career_events").select("*").eq("career_id",career.id),client.from("story_arcs").select("*").eq("career_id",career.id),
client.from("trade_interest").select("*").eq("career_id",career.id),client.from("trade_offers").select("*").eq("career_id",career.id),
client.from("media_posts").select("*").eq("career_id",career.id),client.from("award_snapshots").select("*").eq("career_id",career.id),
client.from("milestones").select("*").eq("career_id",career.id),client.from("relationships").select("*").eq("career_id",career.id)
]);Object.assign(out,{teams:teams||[],seasons:seasons||[],games:games||[],universe_games:universeGames||[],world_settings:world||[],team_stints:stints||[],player_game_stats:stats||[],game_notables:notables||[],injuries:injuries||[],career_events:events||[],story_arcs:arcs||[],trade_interest:interest||[],trade_offers:offers||[],media_posts:media||[],award_snapshots:awards||[],milestones:milestones||[],relationships:relationships||[]});return new NextResponse(JSON.stringify(out,null,2),{headers:{"content-type":"application/json","content-disposition":`attachment; filename="career-universe-${universe.id}-${new Date().toISOString().slice(0,10)}.json"`}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e)},{status:apiStatus(e)})}}
