import Link from "next/link";
import {pageContext,fetchPaged} from "@/lib/universe";
import {summarizeStats,summarizeCareerMarks} from "@/lib/stats";
import {langOf} from "@/lib/i18n";
import {label,prose} from "@/lib/labels";
import {localDate} from "@/lib/format";
import {Section,MetricStrip,EmptyState} from "@/components/Editorial";
import PlayerIdentity from "@/components/PlayerIdentity";
import TeamBadge from "@/components/TeamBadge";
import CareerMarks from "@/components/CareerMarks";
import CareerHonors from "@/components/CareerHonors";
import {gameOpponent} from "@/lib/game-opponent";
export const dynamic="force-dynamic";
export default async function Page(){
 const {client,career,universe}=await pageContext();const lang=langOf(universe),en=lang==="en";
 const [stats,{data:stints},events,{data:injuries},milestones]=await Promise.all([
  fetchPaged((from,to)=>client.from("player_game_stats").select("*,game:games(game_day,season_id,home_team_id,away_team_id,home:teams!games_home_team_id_fkey(*),away:teams!games_away_team_id_fkey(*))").eq("career_id",career.id).order("id").range(from,to)),
  client.from("team_stints").select("*,teams(*)").eq("career_id",career.id).order("start_date"),
  fetchPaged((from,to)=>client.from("career_events").select("*").eq("career_id",career.id).eq("language",lang).order("event_date",{ascending:false}).order("id").range(from,to)),
  client.from("injuries").select("*").eq("career_id",career.id).order("start_date",{ascending:false}),
  fetchPaged((from,to)=>client.from("milestones").select("*").eq("career_id",career.id).eq("language",lang).order("achieved_at",{ascending:false}).order("id").range(from,to))
 ]);const s=summarizeStats(stats);stats.sort((a,b)=>String(b.game?.game_day).localeCompare(String(a.game?.game_day)));
 return <><PlayerIdentity career={career} universe={universe} language={lang}/><nav className="sectionNav" aria-label={en?"Career sections":"Karrierebereiche"}>{[["#career-totals",en?"Overview":"Überblick"],["#game-log",en?"Game log":"Spiele"],["#records",en?"Records":"Bestleistungen"],["#journal",en?"Journal":"Chronik"],["#honors",en?"Achievements":"Erfolge"]].map(([href,title])=><Link href={href} key={href}>{title}</Link>)}</nav><Section id="career-totals" title={en?"Career totals":"Die Karriere in Zahlen"}><MetricStrip items={[{label:en?"Appearances":"Einsätze",value:s.games},{label:"PPG",value:s.ppg.toFixed(1)},{label:"RPG",value:s.rpg.toFixed(1)},{label:"APG",value:s.apg.toFixed(1)},{label:"SPG",value:s.spg.toFixed(1)},{label:"BPG",value:s.bpg.toFixed(1)}]}/></Section>
 <Section title={en?"The jerseys you wore":"Die Trikots deiner Karriere"}><ol className="stintHistory">{stints?.map(x=><li key={x.id}><TeamBadge team={x.teams}/><div><h3>{x.teams?.city} {x.teams?.name}</h3><p>{localDate(x.start_date,lang)} – {x.end_date?localDate(x.end_date,lang):(en?"today":"heute")}</p></div></li>)}</ol></Section>
 <Section id="records" title={en?"Career highs & big games":"Bestleistungen & große Spiele"}><CareerMarks marks={summarizeCareerMarks(stats)} language={lang}/></Section>
 <div className="editorialGrid"><Section id="journal" title={en?"Career journal":"Die Chronik"}>{events.length?<ol className="timeline">{events.map(x=><li className="timelineItem" key={x.id}><small>{localDate(x.event_date,lang)} · {label(x.event_type,lang)}</small><h3>{x.title||label(x.event_type,lang)}</h3><p>{x.description}</p></li>)}</ol>:<EmptyState title={en?"A career starts with a game":"Eine Karriere beginnt mit einem Spiel"} href="/schedule" action={en?"Open schedule":"Zum Spielplan"}/>}</Section><aside><Section title={en?"Medical history":"Die Krankenakte"} id="injuries">{injuries?.length?injuries.map(x=><article className="railStory" key={x.id}><small>{localDate(x.start_date,lang)} · {label(x.severity,lang)}</small><h3>{prose(x,"injury",lang,en?"Injury":"Verletzung")}</h3><p>{label(x.status,lang)}{x.end_date?` · ${localDate(x.end_date,lang)}`:""}</p></article>):<p>{en?"No injuries recorded.":"Keine Verletzungen verzeichnet."}</p>}</Section><Section title={en?"Milestones":"Meilensteine"}>{milestones.map(x=><article className="railStory" key={x.id}><h3>{x.title}</h3><p>{x.description}</p></article>)}{!milestones.length&&<p className="muted">{en?"Your first milestone is ahead.":"Dein erster Meilenstein liegt noch vor dir."}</p>}</Section></aside></div>
 <Section id="game-log" title={en?"Every game, on record":"Spiel für Spiel"}>{stats.length?<div className="tableWrap" tabIndex={0} role="region" aria-label={en?"Career game log, scroll horizontally":"Karriere-Spielprotokoll, horizontal scrollbar"}><table><thead><tr>{[en?"Date":"Datum",en?"Opponent":"Gegner","PTS","REB","AST","STL","BLK","TO","FG",en?"Appearance":"Einsatz"].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{stats.map(x=>{const opponent=gameOpponent(x.team_id,x.game);return <tr key={x.id}><td><Link href={"/game/"+x.game_id}>{localDate(x.game?.game_day,lang)}</Link></td><td>{opponent?.team?<Link className="gameLogOpponent" href={"/game/"+x.game_id}><TeamBadge team={opponent.team} small/><span><strong>{opponent.team.abbreviation}</strong><small>{opponent.home?(en?"Home":"Heim"):(en?"Away":"Auswärts")}</small></span></Link>:"—"}</td>{["points","rebounds","assists","steals","blocks","turnovers"].map(k=><td key={k}>{x.appearance_status==="played"?x[k]:"—"}</td>)}<td>{x.appearance_status==="played"?`${x.fgm}/${x.fga}`:"—"}</td><td>{label(x.appearance_status,lang)}{x.ejected?" · Ejection":""}{x.fouled_out?` · ${en?"Fouled out":"Ausgefoult"}`:""}</td></tr>;})}</tbody></table></div>:<p className="muted">{en?"No games recorded yet.":"Noch kein Spiel verzeichnet."}</p>}</Section><CareerHonors/></>;
}
