"use client";
import {useState} from "react";
import {FCLabel} from "@/components/FootballFieldErrors";
import {FCForm,FCField,FCSelect} from "@/components/FootballForms";
import {FootballClubField,FootballLeagueClubFields} from "@/components/FootballCatalogFields";
export default function FootballTransferForm({profile:p,squad,date,en=false}:{profile:any;squad:any[];date:string;en?:boolean}){
 const [direction,setDirection]=useState(p.mode==="manager"?"in":"career"),[squadId,setSquadId]=useState("");const player=squad.find(x=>x.id===squadId);
 return <FCForm action="transfer" validation={{mode:p.mode,club:p.club_name,currentDate:date,budget:Number(p.budget)}} initial={{expected:p.updated_at}} en={en} label={en?"Record transfer":"Transfer eintragen"}>
 {p.mode==="manager"&&<FCLabel name="direction" label={en?"Transfer direction":"Transferart"}><select name="direction" value={direction} onChange={e=>{setDirection(e.target.value);setSquadId("");}}><option value="in">{en?"Incoming player":"Spielerzugang"}</option><option value="out">{en?"Outgoing player":"Spielerabgang"}</option><option value="career">{en?"My club change":"Mein Vereinswechsel"}</option></select></FCLabel>}{p.mode==="player"&&<input type="hidden" name="direction" value="career"/>}
 {direction==="out"&&<FCLabel name="squad_id" label={en?"Squad player (optional)":"Kaderspieler (optional)"}><select name="squad_id" value={squadId} onChange={e=>setSquadId(e.target.value)}><option value="">{en?"Enter name manually":"Name manuell eintragen"}</option>{squad.filter(x=>["available","injured","suspended"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></FCLabel>}
 {direction!=="career"&&(player?<><input type="hidden" name="player_name" value={player.name}/><p>{player.name}</p></>:<FCField name="player_name" label={en?"Player name":"Spielername"} required maxLength={100}/>)}
 {direction==="career"&&<FootballLeagueClubFields key="career" league={p.league} clubName="to_club" clubLabel={en?"New club":"Neuer Verein"} leagueLabel={en?"New league":"Neue Liga"} en={en}/>}<div className={direction==="career"?"":"grid2"}>{direction!=="career"&&<FootballClubField key={direction} name={direction==="in"?"from_club":"to_club"} label={direction==="in"?(en?"From club":"Abgebender Verein"):(en?"New club":"Neuer Verein")} league={p.league} en={en}/>}<FCField name="transfer_date" label={en?"Transfer date":"Transferdatum"} type="date" value={date} required/></div>
 <div className="grid3"><FCSelect name="kind" label={en?"Type":"Wechselart"} value={p.mode==="manager"&&direction==="career"?"manager":"permanent"} options={p.mode==="manager"&&direction==="career"?[["manager",en?"Manager move":"Trainerwechsel"]]:[["permanent",en?"Permanent":"Festwechsel"],["loan",en?"Loan":"Leihe"],["free",en?"Free transfer":"Ablösefrei"],["return",en?"Return":"Rückkehr"]]}/><FCField name="fee" label={en?"Fee (€)":"Ablöse (€)"} type="number" value={0} min={0} step="0.01" required/><FCField name="weekly_wage" label={en?"New weekly wage (€)":"Neues Wochengehalt (€)"} type="number" value={direction==="career"?p.weekly_wage:0} min={0} step="0.01"/></div>
 <FCField name="contract_until" label={en?"Contract until":"Vertrag bis"} type="date"/>{direction==="career"&&<FCField name="club_color" label={en?"New club colour":"Neue Vereinsfarbe"} type="color" value={p.club_color}/>}<FCLabel name="notes" label={en?"Transfer notes":"Transfernotizen"}><textarea name="notes" rows={3} maxLength={2000}/></FCLabel>
 <p className="finePrint">{direction==="career"?(en?"Your existing results and statistics keep their original club. Add the new club's fixtures after the move.":"Bisherige Spiele und Statistiken behalten ihren damaligen Verein. Ergänze nach dem Wechsel die Partien deines neuen Vereins."):(en?"Transfer fees update your budget. Selected departing squad players leave the active lineup; add incoming players to the squad with their details.":"Ablösen aktualisieren dein Budget. Ausgewählte Abgänge verlassen die Aufstellung; ergänze Zugänge mit ihren Daten im Kader.")}</p>
 </FCForm>;
}
