"use client";
import {useState,useEffect,type ReactNode,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {formations,positions} from "@/lib/football";
import StatusMessage from "@/components/StatusMessage";
import {FootballLeagueClubFields,FootballClubField,FootballCompetitionField} from "@/components/FootballCatalogFields";

export async function footballRequest(action:string,body:unknown){const response=await fetch(`/api/fc/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||"Request failed");return result;}
export function FCForm({action,children,label,en=false,initial={},navigate=false}:{action:string;children:ReactNode;label?:string;en?:boolean;initial?:Record<string,unknown>;navigate?:boolean}){
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");setSaved(false);const entries=Object.fromEntries(new FormData(event.currentTarget)),body:any={...initial,...entries};
 body.extra_time=entries.extra_time==="on";const stats:any={};for(const [key,value] of Object.entries(entries))if(key.startsWith("stats."))stats[key.slice(6)]=value;if(Object.keys(stats).length)body.player_stats=stats;
 try{const result=await footballRequest(action,body);setSaved(true);if(navigate&&result.href)router.push(result.href);router.refresh();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}}
 return <form className="fcForm" onSubmit={submit}>{error&&<StatusMessage tone="error">{error}</StatusMessage>}{saved&&<StatusMessage tone="success">{en?"Saved.":"Gespeichert."}</StatusMessage>}<fieldset disabled={busy}>{children}<button type="submit">{busy?(en?"Saving…":"Wird gespeichert…"):(label|| (en?"Save":"Speichern"))} →</button></fieldset></form>;
}
export function FCAction({action,body,children,en=false}:{action:string;body:unknown;children:ReactNode;en?:boolean}){const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");return <div className="fcAction"><button className="secondaryButton" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);setMessage("");try{await footballRequest(action,body);setMessage(en?"Saved.":"Gespeichert.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}}>{busy?"…":children}</button>{message&&<p role="status">{message}</p>}</div>;}
export function FCField({name,label,value="",type="text",min,max,step,required=false,placeholder,maxLength}:{name:string;label:string;value?:any;type?:string;min?:number;max?:number;step?:string|number;required?:boolean;placeholder?:string;maxLength?:number}){return <label>{label}<input name={name} type={type} defaultValue={value??""} min={min} max={max} step={step} required={required} placeholder={placeholder} maxLength={maxLength}/></label>;}
export function FCSelect({name,label,value,options}:{name:string;label:string;value?:any;options:(string|[string,string])[]}){return <label>{label}<select name={name} defaultValue={value}>{options.map(o=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o}>{o}</option>)}</select></label>;}
export function FootballCreate({en=false}:{en?:boolean}){const [mode,setMode]=useState("player"),year=new Date().getFullYear();return <FCForm action="create" en={en} navigate label={en?"Begin career":"Karriere beginnen"}>
 <div className="fcModePicker"><button type="button" className={mode==="player"?"selected":"secondaryButton"} onClick={()=>setMode("player")}>{en?"Player career":"Spielerkarriere"}</button><button type="button" className={mode==="manager"?"selected":"secondaryButton"} onClick={()=>setMode("manager")}>{en?"Manager career":"Trainerkarriere"}</button></div><input type="hidden" name="mode" value={mode}/>
 <div className="grid2"><FCField name="name" label={en?"Career name":"Karrierename"} required maxLength={100} placeholder={en?"My road to the top":"Mein Weg an die Spitze"}/><FCField name="person_name" label={mode==="player"?(en?"Player name":"Spielername"):(en?"Manager name":"Trainername")} required maxLength={100}/></div>
 <FootballLeagueClubFields en={en} includeClubs/><FCField name="club_color" label={en?"Club colour":"Vereinsfarbe"} type="color" value="#e5bf24"/>
 {mode==="player"?<div className="grid3"><FCSelect name="position" label="Position" value="ST" options={positions}/><FCField name="overall" label="OVR" type="number" value={75} min={1} max={99} required/><FCField name="jersey_number" label={en?"Shirt number":"Trikotnummer"} type="number" min={1} max={99}/></div>:<div className="grid2"><FCSelect name="formation" label="Formation" value="4-2-3-1" options={Object.keys(formations)}/><FCField name="budget" label={en?"Transfer budget (€)":"Transferbudget (€)"} type="number" value={0} min={0} step="0.01" required/></div>}
 <details className="formDisclosure"><summary>{en?"Personal details & contract":"Persönliche Daten & Vertrag"}</summary><div className="grid2"><FCField name="nationality" label={en?"Nationality":"Nationalität"}/><FCField name="birth_date" label={en?"Date of birth":"Geburtsdatum"} type="date"/><FCField name="weekly_wage" label={en?"Weekly wage (€)":"Wochengehalt (€)"} type="number" value={0} min={0} step="0.01"/><FCField name="contract_until" label={en?"Contract until":"Vertrag bis"} type="date"/></div></details>
 <div className="grid3"><FCField name="season_name" label={en?"Season":"Saison"} value={`${year}/${String(year+1).slice(-2)}`} required maxLength={40}/><FCField name="universe_date" label={en?"Start date":"Startdatum"} type="date" value={`${year}-07-01`} required/><FCField name="end_date" label={en?"Season ends":"Saisonende"} type="date" value={`${year+1}-06-30`} required/></div><FCSelect name="language" label={en?"Career language":"Karrieresprache"} value={en?"en":"de"} options={[["de","Deutsch"],["en","English"]]}/>

 </FCForm>;}
export function FootballMatchForm({profile,season,match:initialMatch,en=false}:{profile:any;season:any;match?:any;en?:boolean}){
 const [match,setMatch]=useState<any>(initialMatch),[scanVersion,setScanVersion]=useState(0);
 const [status,setStatus]=useState(initialMatch?.status||"completed"),[appearance,setAppearance]=useState(initialMatch?.player_stats?.appearance||"played");const own=!match||[match.home_club,match.away_club].includes(match.tracked_club),s=match?.player_stats||{};
 useEffect(()=>{setMatch(initialMatch);setStatus(initialMatch?.status||"completed");setAppearance(initialMatch?.player_stats?.appearance||"played");setScanVersion(v=>v+1);},[initialMatch?.id,initialMatch?.updated_at]);
 useEffect(()=>{const listener=(event:Event)=>{const fields=(event as CustomEvent).detail;if(!fields)return;const form=document.querySelector<HTMLFormElement>("#entry .fcForm"),values:any=form?Object.fromEntries(new FormData(form)):{},stats:any={...(match?.player_stats||{})};for(const [key,value] of Object.entries(values))if(key.startsWith("stats."))stats[key.slice(6)]=value;for(const [key,value] of Object.entries(fields)){if(value==null)continue;if(key.startsWith("stats."))stats[key.slice(6)]=value;else values[key]=value;}const personal=Object.keys(fields).some(k=>k.startsWith("stats.")&&fields[k]!=null);setMatch({...match,...values,player_stats:{...stats,appearance:personal?"played":appearance},extra_time:values.extra_time==="on"});setStatus("completed");if(personal)setAppearance("played");setScanVersion(v=>v+1);};document.addEventListener("fc-scan-values",listener);return()=>document.removeEventListener("fc-scan-values",listener);},[match,appearance]);
 return <FCForm key={scanVersion} action="match" en={en} navigate initial={{id:match?.id||null,expected:match?.updated_at||null,season_id:match?.season_id||season.id,tracked_club:match?.tracked_club||profile.club_name}} label={en?"Save match":"Spiel speichern"}>
 <div className="grid3"><FCField name="match_date" label={en?"Match date":"Spieldatum"} type="date" value={match?.match_date||season.start_date} required/><FootballCompetitionField value={match?.competition||season.league} en={en}/><FCSelect name="stage" label={en?"Type":"Spielart"} value={match?.stage||"league"} options={[["league",en?"League":"Liga"],["cup",en?"Cup":"Pokal"],["international",en?"International":"International"],["friendly",en?"Friendly":"Testspiel"],["playoff","Playoff"]]}/></div>
 <div className="grid3"><FootballClubField name="home_club" label={en?"Home":"Heimverein"} value={match?.home_club||profile.club_name} league={season.league} en={en}/><FootballClubField name="away_club" label={en?"Away":"Gastverein"} value={match?.away_club} league={season.league} en={en}/><FCField name="round" label={en?"Matchday / round":"Spieltag / Runde"} type="number" min={1} value={match?.round}/></div>
 <label>Status<select name="status" value={status} onChange={e=>setStatus(e.target.value)}><option value="scheduled">{en?"Scheduled fixture":"Geplante Partie"}</option><option value="completed">{en?"Final result":"Endergebnis"}</option></select></label>
 {status==="completed"&&<><div className="fcScoreInputs"><FCField name="home_score" label={en?"Home goals":"Tore Heim"} type="number" min={0} max={99} value={match?.home_score} required/><span aria-hidden="true">:</span><FCField name="away_score" label={en?"Away goals":"Tore Gast"} type="number" min={0} max={99} value={match?.away_score} required/></div>
 <details className="formDisclosure" open={match?.extra_time||match?.home_penalties!=null||undefined}><summary>{en?"Extra time & penalty shootout":"Verlängerung & Elfmeterschießen"}</summary><p className="finePrint">{en?"Enter the score after extra time above; shootout goals separately below.":"Oben steht der Spielstand nach der Verlängerung. Treffer im Elfmeterschießen stehen separat darunter."}</p><label className="fcCheckbox"><input type="checkbox" name="extra_time" defaultChecked={match?.extra_time}/>{en?"Extra time played":"Verlängerung gespielt"}</label><div className="grid2"><FCField name="home_penalties" label={en?"Shootout: home":"Elfmeterschießen: Heim"} type="number" min={0} max={99} value={match?.home_penalties}/><FCField name="away_penalties" label={en?"Shootout: away":"Elfmeterschießen: Gast"} type="number" min={0} max={99} value={match?.away_penalties}/></div></details>
 {profile.mode==="player"&&own&&<><h3>{en?"Your performance":"Deine Leistung"}</h3><label>{en?"Appearance":"Einsatzstatus"}<select name="stats.appearance" value={appearance} onChange={e=>setAppearance(e.target.value)}>{[["played",en?"Played":"Gespielt"],["bench",en?"Unused substitute":"Ohne Einsatz"],["injured",en?"Injured":"Verletzt"],["suspended",en?"Suspended":"Gesperrt"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{appearance==="played"&&<><div className="grid3"><FCField name="stats.minutes" label={en?"Minutes":"Minuten"} type="number" min={0} max={120} value={s.minutes}/><FCField name="stats.goals" label={en?"Goals":"Tore"} type="number" min={0} max={99} value={s.goals??0} required/><FCField name="stats.assists" label="Assists" type="number" min={0} max={99} value={s.assists??0} required/></div><div className="grid3"><FCField name="stats.rating" label="Matchrating (0–10)" type="number" min={0} max={10} step="0.1" value={s.rating}/><FCField name="stats.yellow_cards" label={en?"Yellow cards":"Gelbe Karten"} type="number" min={0} max={2} value={s.yellow_cards??0}/><FCField name="stats.red_cards" label={en?"Red cards":"Rote Karten"} type="number" min={0} max={1} value={s.red_cards??0}/></div><details className="formDisclosure"><summary>{en?"More player statistics":"Weitere Spielerwerte"}</summary><div className="grid3">{[["shots",en?"Shots":"Schüsse"],["shots_on_target",en?"On target":"Aufs Tor"],["passes",en?"Passes":"Pässe"],["pass_accuracy",en?"Pass accuracy (%)":"Passquote (%)"],["tackles","Tackles"],["interceptions",en?"Interceptions":"Abgefangene Bälle"],["saves",en?"Saves":"Paraden"]].map(([key,label])=><FCField key={key} name={`stats.${key}`} label={label} type="number" min={0} max={key==="pass_accuracy"?100:999} step={key==="pass_accuracy"?"0.1":"1"} value={s[key]}/>)}</div></details></>}</>}
 <details className="formDisclosure"><summary>{en?"Team statistics":"Teamstatistiken"}</summary><p className="finePrint">{en?"Statistics for the tracked club. Leave unknown values blank.":"Werte des erfassten Vereins. Unbekannte Werte bleiben leer."}</p><div className="grid2"><FCField name="possession" label={en?"Possession (%)":"Ballbesitz (%)"} type="number" min={0} max={100} step="0.1" value={match?.possession}/><FCField name="xg" label="xG" type="number" min={0} max={99} step="0.01" value={match?.xg}/><FCField name="shots" label={en?"Shots":"Schüsse"} type="number" min={0} value={match?.shots}/><FCField name="shots_on_target" label={en?"Shots on target":"Schüsse aufs Tor"} type="number" min={0} value={match?.shots_on_target}/></div></details></>}
 <label>{en?"Match notes":"Spielnotizen"}<textarea name="notes" rows={4} maxLength={6000} defaultValue={match?.notes||""} placeholder={en?"Key moments, atmosphere, your take…":"Schlüsselmomente, Stimmung, dein Fazit …"}/></label><p className="finePrint">{en?"Editing a saved match keeps its existing coverage. Update reports separately when you want to.":"Beim Bearbeiten bleiben vorhandene Medienberichte erhalten. Aktualisiere sie bei Bedarf anschließend separat."}</p>
 </FCForm>;
}
export function FootballSquadForm({player,en=false}:{player?:any;en?:boolean}){return <FCForm action="squad" en={en} initial={{id:player?.id||null,expected:player?.updated_at||null}} label={en?"Save player":"Spieler speichern"}><div className="grid3"><FCField name="name" label={en?"Player name":"Spielername"} value={player?.name} required maxLength={100}/><FCSelect name="position" label="Position" value={player?.position||"ST"} options={positions}/><FCField name="overall" label="OVR" type="number" value={player?.overall||75} min={1} max={99} required/></div><div className="grid3"><FCField name="age" label={en?"Age":"Alter"} type="number" min={14} max={65} value={player?.age}/><FCField name="nationality" label={en?"Nationality":"Nationalität"} value={player?.nationality}/><FCField name="jersey_number" label={en?"Shirt number":"Trikotnummer"} type="number" min={1} max={99} value={player?.jersey_number}/></div><div className="grid2"><FCSelect name="status" label="Status" value={player?.status||"available"} options={[["available",en?"Available":"Verfügbar"],["injured",en?"Injured":"Verletzt"],["suspended",en?"Suspended":"Gesperrt"],["loaned",en?"On loan":"Verliehen"],["departed",en?"Departed":"Abgegangen"]]}/><FCSelect name="role" label={en?"Role":"Rolle"} value={player?.role||"rotation"} options={[["key",en?"Key player":"Schlüsselspieler"],["starter",en?"Starter":"Stammspieler"],["rotation","Rotation"],["prospect",en?"Prospect":"Talent"]]}/><FCField name="market_value" label={en?"Market value (€)":"Marktwert (€)"} type="number" min={0} step="0.01" value={player?.market_value||0}/><FCField name="weekly_wage" label={en?"Weekly wage (€)":"Wochengehalt (€)"} type="number" min={0} step="0.01" value={player?.weekly_wage||0}/><FCField name="contract_until" label={en?"Contract until":"Vertrag bis"} type="date" value={player?.contract_until}/></div><label>{en?"Notes":"Notizen"}<textarea name="notes" rows={3} maxLength={2000} defaultValue={player?.notes||""}/></label></FCForm>;}
export function FootballLineup({squad,formation,expected,en=false}:{expected:string;squad:any[];formation:keyof typeof formations;en?:boolean}){
 const router=useRouter(),[shape,setShape]=useState<keyof typeof formations>(formation in formations?formation:"4-2-3-1"),[slots,setSlots]=useState<(string|null)[]>(Array.from({length:11},(_,i)=>squad.find(p=>p.lineup_slot===i)?.id||null)),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const ys=shape==="3-5-2"?[91,72,72,72,45,45,45,45,45,18,18]:shape==="4-3-3"?[91,70,70,70,70,45,45,45,18,18,18]:shape==="4-4-2"?[91,70,70,70,70,44,44,44,44,18,18]:shape==="4-5-1"?[91,70,70,70,70,44,44,44,44,44,18]:[91,72,72,72,72,54,54,33,33,33,13];
 const available=squad.filter(p=>p.status==="available");
 return <section><label>Formation<select value={shape} onChange={e=>setShape(e.target.value as keyof typeof formations)}>{Object.keys(formations).map(f=><option key={f}>{f}</option>)}</select></label><div className="fcPitch" aria-label={en?"Starting eleven":"Startelf"}><div className="fcPitchLines" aria-hidden="true"/><div className="fcPitchCircle" aria-hidden="true"/>{formations[shape].map((pos,i)=>{const row=ys.map((y,j)=>({y,j})).filter(a=>a.y===ys[i]),x=100*(row.findIndex(a=>a.j===i)+1)/(row.length+1);return <label key={i} className="fcPitchSlot" style={{left:`${x}%`,top:`${ys[i]}%`}}><span>{pos}</span><select aria-label={`${pos} · ${i+1}`} value={slots[i]||""} onChange={e=>setSlots(old=>old.map((id,j)=>j===i?e.target.value||null:id))}><option value="">{en?"Select":"Wählen"}</option>{available.filter(p=>!slots.includes(p.id)||slots[i]===p.id).map(p=><option value={p.id} key={p.id}>{p.name} · {p.overall}</option>)}</select></label>;})}</div><p className="finePrint">{slots.filter(Boolean).length}/11 {en?"positions filled. Only available players can start.":"Positionen besetzt. Nur verfügbare Spieler können aufgestellt werden."}</p><button disabled={busy} onClick={async()=>{setBusy(true);setMessage("");try{await footballRequest("lineup",{formation:shape,slots,expected});setMessage(en?"Lineup saved.":"Aufstellung gespeichert.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}}>{busy?"…":en?"Save lineup":"Aufstellung speichern"}</button>{message&&<p role="status">{message}</p>}</section>;
}
