import Link from "next/link";
import {footballOutlets,internationalFootballOutlets} from "@/lib/football-outlets";
import {matchResult,type FootballMatch} from "@/lib/football";
import ClubMark from "@/components/FootballClubBadge";
export {default as ClubMark} from "@/components/FootballClubBadge";
export function FootballScore({match,compact=false,en=false}:{match:FootballMatch;compact?:boolean;en?:boolean}){return <div className={`fcScoreboard${compact?" compact":""}`}><div className="fcScoreMeta"><span>{match.competition} {match.round?`/ ${match.round}`:""}</span><time>{match.match_date}</time></div><div className="fcScoreTeams"><div><ClubMark name={match.home_club} league={match.competition}/><strong>{match.home_club}</strong><small>{en?"HOME":"HEIM"}</small></div><div className="fcScoreValue">{match.status==="completed"?<><b>{match.home_score}</b><span>:</span><b>{match.away_score}</b></>:<span>VS</span>}{match.home_penalties!=null&&<small>{match.home_penalties}:{match.away_penalties} {en?"pens":"i. E."}</small>}</div><div><ClubMark name={match.away_club} league={match.competition}/><strong>{match.away_club}</strong><small>{en?"AWAY":"GAST"}</small></div></div><div className="fcScoreFoot">{match.status==="completed"?(en?"FULL TIME":"ABPFIFF"):(en?"UP NEXT":"ALS NÄCHSTES")}{match.extra_time&&` · ${en?"EXTRA TIME":"VERLÄNGERUNG"}`}</div></div>;}
export function FootballMatchRow({match,en=false}:{match:FootballMatch;en?:boolean}){const result=matchResult(match);return <Link className="fcMatchRow" href={`/fc/match/${match.id}`}><div><time>{match.match_date}</time><small>{match.competition}</small></div><div className="fcMatchClubs"><span><ClubMark name={match.home_club} league={match.competition}/>{match.home_club}</span><span><ClubMark name={match.away_club} league={match.competition}/>{match.away_club}</span></div><strong>{match.status==="completed"?`${match.home_score}:${match.away_score}`:"—"}{match.home_penalties!=null&&<small>{match.home_penalties}:{match.away_penalties} i. E.</small>}</strong><span className={`fcResult ${result||""}`}>{result?(en?result:({W:"S",D:"U",L:"N"})[result]):"→"}</span></Link>;}
export function FootballMediaCard({post,en=false}:{post:any;en?:boolean}){
 const labels:Record<string,string>={recap:en?"MATCH REPORT":"SPIELBERICHT",broadcast:en?"TV ANALYSIS":"TV-ANALYSE",analysis:en?"ANALYSIS":"ANALYSE",local:en?"LOCAL PRESS":"LOKALE PRESSE",international:en?"INTERNATIONAL PRESS":"INTERNATIONALE PRESSE",statistics:en?"DATA DESK":"STATISTIK",social:"SOCIAL",fan:en?"FAN VOICE":"FANSTIMME",critical:en?"SECOND LOOK":"ZWEITER BLICK"},outlet=[...footballOutlets,...internationalFootballOutlets].find(x=>x.name===post.outlet);
 return <article className={`fcMediaCard ${post.kind}`}><div><span className="eyebrow">{labels[post.kind]||post.kind}</span><small>{post.author}</small></div>{post.outlet&&<strong className="fcMediaOutlet">{post.outlet}</strong>}<h3>{post.headline}</h3><p>{post.body}</p><small className="fcMediaSource">{post.source==="openai"?(en?"AI-generated career simulation":"KI-generierte Karrieresimulation"):(en?"Simulated career report":"Simulierter Karrierebericht")}{post.model&&` · ${post.model==="gpt-6.1-sol"?"GPT 6.1 Sol":post.model}`}</small>{outlet&&<a className="fcOutletLink" href={outlet.url} target="_blank" rel="noreferrer">{en?"Outlet website":"Portal-Website"} ↗</a>}{post.match_id&&<Link href={`/fc/match/${post.match_id}`}>{en?"Match file":"Spielakte"} →</Link>}</article>;
}
export function FCEmpty({en=false,children,href}:{en?:boolean;children:React.ReactNode;href?:string}){return <div className="fcEmpty"><span>00 / {en?"THE NEXT CHAPTER":"DAS NÄCHSTE KAPITEL"}</span><p>{children}</p>{href&&<Link className="button" href={href}>{en?"Get started":"Loslegen"} →</Link>}</div>;}
export function FCMetrics({items}:{items:{label:string;value:React.ReactNode}[]}){return <dl className="fcMetrics">{items.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>;}
