"use client";
import {useState} from "react";
import {optimizeImages} from "@/lib/image-optimize";
export default function FootballScreenshot({en=false,matchId}:{en?:boolean;matchId:string}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState("");
 async function scan(files:File[]){if(!files.length)return;setBusy(true);setError("");setResult(null);try{const images=await optimizeImages(files,2,"/api/fc/image-normalize"),r=await fetch("/api/fc/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({match_id:matchId,images:images.map(x=>x.dataUrl)})}),j=await r.json();if(!r.ok)throw Error(j.error);setResult(j);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function apply(){if(!result)return;document.dispatchEvent(new CustomEvent("fc-scan-values",{detail:result.fields}));document.querySelector("#entry .fcForm")?.scrollIntoView({behavior:"smooth",block:"start"});}

 return <details className="fcScreenshot"><summary>{en?"Read scoreboard screenshot":"Werte aus Screenshot lesen"}</summary><p className="finePrint">{en?"Upload up to two images. Review extracted values before saving; nothing is saved automatically.":"Lade bis zu zwei Bilder hoch. Prüfe erkannte Werte vor dem Speichern; es wird nichts automatisch gespeichert."}</p><label>{en?"Scoreboard / player statistics":"Scoreboard / Spielerstatistik"}<input type="file" accept="image/*" multiple disabled={busy} onChange={e=>{scan(Array.from(e.target.files||[]).slice(0,2));e.target.value="";}}/></label>{busy&&<p role="status">{en?"Reading image…":"Bild wird gelesen …"}</p>}{error&&<p role="alert" className="fcNotice">{error}</p>}{result&&<><p>{result.notes}</p><dl className="fcScanValues">{Object.entries(result.fields||{}).filter(([,value])=>value!=null).map(([key,value])=><div key={key}><dt>{({home_score:en?"Home goals":"Tore Heim",away_score:en?"Away goals":"Tore Gast","stats.minutes":en?"Minutes":"Minuten","stats.goals":en?"Goals":"Tore","stats.assists":"Assists","stats.rating":"Matchrating","stats.shots":en?"Player shots":"Spielerschüsse","stats.shots_on_target":en?"Player shots on target":"Spielerschüsse aufs Tor","stats.passes":en?"Passes":"Pässe","stats.pass_accuracy":en?"Pass accuracy":"Passquote","stats.tackles":"Tackles","stats.interceptions":en?"Interceptions":"Abgefangene Bälle","stats.saves":en?"Saves":"Paraden",possession:en?"Possession":"Ballbesitz",shots:en?"Team shots":"Teamschüsse",shots_on_target:en?"Team shots on target":"Teamschüsse aufs Tor",xg:"xG"} as Record<string,string>)[key]||key}</dt><dd>{String(value)}</dd></div>)}</dl><button type="button" className="secondaryButton" onClick={apply}>{en?"Copy values into form":"Werte ins Formular übernehmen"}</button></>}</details>;
}
