"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {imageErrorMessage} from "@/lib/image-format";
import {optimizeImages} from "@/lib/image-optimize";
import {statKeys,statLabels} from "@/lib/game-input";
import {normalizeAbbr} from "@/lib/team-map";
import StatusMessage from "@/components/StatusMessage";
import {prose} from "@/lib/labels";
export default function QuickGameEntry({game,existingStat,existingResult,existingNotables=[],language,autoMedia=true}:{game:any;existingStat:any;existingResult:any;existingNotables?:any[];language:"de"|"en";autoMedia?:boolean}){
 const router=useRouter(),formRef=useRef<HTMLFormElement>(null),en=language==="en",editing=Boolean(existingStat);
 const [busy,setBusy]=useState(false),[scanning,setScanning]=useState(false),[message,setMessage]=useState(""),[tone,setTone]=useState<"error"|"success"|"warning"|"info">("info"),[status,setStatus]=useState(existingStat?.appearance_status||"played"),[confidence,setConfidence]=useState<Record<string,number>>({}),[lastImages,setLastImages]=useState<{images:string[];imageMeta:any[]}|null>(null),[scanInfo,setScanInfo]=useState(""),[review,setReview]=useState(false);
 const lock=busy||scanning;
 function field(name:string,value:unknown){const input=formRef.current?.elements.namedItem(name) as HTMLInputElement|null;if(input)input.value=value==null?"":String(value);}
 async function requestScan(payload:{images:string[];imageMeta:any[]},precision:"low"|"high"){
  setScanning(true);setMessage("");try{
   const response=await fetch("/api/admin/scoreboard-scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,expectedGameId:game.id,precision})});const data=await response.json();if(!response.ok)throw Error(data.error);
   const scan=data.scan||{},home=normalizeAbbr(game.home?.abbreviation||""),away=normalizeAbbr(game.away?.abbreviation||"");
   const a=normalizeAbbr(scan.team_a||""),b=normalizeAbbr(scan.team_b||"");let homeScore=null,awayScore=null;
   if(a===home&&b===away){homeScore=scan.team_a_score;awayScore=scan.team_b_score;}
   else if(a===away&&b===home){homeScore=scan.team_b_score;awayScore=scan.team_a_score;}
   else if(scan.orientation_confident&&normalizeAbbr(scan.home_team||"")===home&&normalizeAbbr(scan.away_team||"")===away){homeScore=scan.home_score;awayScore=scan.away_score;}
   field("homeScore",homeScore);field("awayScore",awayScore);
   if(scan.player_found){for(const key of statKeys)if(!["technical_fouls","flagrant_fouls"].includes(key))field(key,scan.stats?.[key]);}
   setConfidence(scan.field_confidence||{});setReview(true);setTone("warning");
   setMessage(!scan.player_found?(en?"Your player was not found. Player values were not imported; please enter them manually.":"Dein Spieler wurde nicht gefunden. Bitte seine Werte manuell ergänzen."):homeScore===null||awayScore===null?(en?"The matchup or score could not be identified. Review the teams and enter the final score.":"Die Paarung oder der Endstand ist nicht eindeutig. Prüfe die Teams und ergänze das Ergebnis."):(en?"Values imported. Check them against the image and confirm below before saving.":"Werte übernommen. Gleiche sie mit dem Bild ab und bestätige die Prüfung vor dem Speichern."));
  }catch(e){setTone("error");setMessage(e instanceof Error?e.message:String(e));}finally{setScanning(false);}
 }
 async function scan(files:File[]){
  if(!files.length)return;if(files.length>2){setTone("error");setMessage(en?"Choose at most two images.":"Bitte höchstens zwei Bilder wählen.");return;}
  setScanning(true);setMessage("");setLastImages(null);setScanInfo("");try{const optimized=await optimizeImages(files,2);const payload={images:optimized.map(x=>x.dataUrl),imageMeta:optimized.map(x=>({width:x.width,height:x.height,optimizedBytes:x.optimizedBytes}))};setLastImages(payload);setScanInfo(`${optimized.length} ${en?"image(s)":"Bild(er)"} · ${Math.round(optimized.reduce((n,x)=>n+x.optimizedBytes,0)/1024)} KB`);await requestScan(payload,"low");}catch(e){setTone("error");setMessage(imageErrorMessage(e,language));setScanning(false);}
 }
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock)return;setBusy(true);setMessage("");try{
  const f=new FormData(e.currentTarget),stats=Object.fromEntries(statKeys.map(k=>[k,f.get(k)]));
  const response=await fetch("/api/admin/game",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({gameId:game.id,expectedUpdatedAt:existingStat?.updated_at||null,homeScore:f.get("homeScore"),awayScore:f.get("awayScore"),appearanceStatus:status,stats,started:f.get("started")==="on",fouledOut:f.get("fouledOut")==="on",ejected:f.get("ejected")==="on",injured:f.get("injured")==="on",injuryNote:f.get("injuryNote"),storyNotes:f.get("storyNotes"),notableText:f.get("notables"),autoMedia:!editing&&f.get("autoMedia")==="on"})});
  const data=await response.json();if(!response.ok)throw Error(data.error);setTone(data.mediaWarning?"warning":"success");setMessage((en?"Game saved.":"Spiel gespeichert.")+(data.mediaWarning?" "+data.mediaWarning:""));setReview(false);router.refresh();
 }catch(e){setTone("error");setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="quickEntry" id="stats"><div className="sectionHead"><h2>{editing?(en?"Correct the game record":"Den Spieleintrag korrigieren"):(en?"Put this game on record":"Dieses Spiel festhalten")}</h2><span>{game.away?.abbreviation} @ {game.home?.abbreviation}</span></div><div className="screenshotInline"><div><h3>{en?"Start with your box score":"Starte mit deinem Boxscore"}</h3><p>{en?"One image is usually enough. Images are resized before the economy scan. Add a second if scores and player stats are on separate screens.":"Ein Bild reicht meistens. Es wird vor der sparsamen Analyse verkleinert. Ein zweites hilft, wenn Ergebnis und Spielerwerte auf getrennten Ansichten stehen."}</p></div><label className="uploadButton">{scanning?(en?"Reading the image…":"Bild wird gelesen…"):(en?"Choose screenshots":"Screenshots auswählen")}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/heic,image/heif,image/bmp,image/tiff,.jpg,.jpeg,.png,.webp,.gif,.avif,.heic,.heif,.bmp,.tif,.tiff" multiple disabled={lock} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value="";void scan(files);}}/></label></div>
 {scanInfo&&<p className="muted">{scanInfo}</p>}{message&&<StatusMessage tone={tone}>{message}</StatusMessage>}
 {Object.keys(confidence).length>0&&<details className="scanDetails"><summary>{en?"Recognition confidence by field":"Erkennungssicherheit je Wert"}</summary><dl className="confidenceGrid">{Object.entries(confidence).map(([k,v])=><div key={k} className={v<75?"low":"high"}><dt>{statLabels[k]||(k==="home_score"?(en?"Home":"Heim"):k==="away_score"?(en?"Away":"Auswärts"):k)}</dt><dd>{v}%</dd></div>)}</dl><p>{en?"These are model estimates, not guaranteed accuracy.":"Die Werte sind Schätzungen des Modells, keine garantierte Genauigkeit."}</p></details>}
 {lastImages&&Object.values(confidence).some(v=>v<75)&&<button className="secondaryButton" disabled={lock} onClick={()=>requestScan(lastImages,"high")}>{en?"Recheck with higher image detail (extra request)":"Mit höherer Bildauflösung nachprüfen (zusätzliche Anfrage)"}</button>}
 {editing&&<p className="formHelp">{en?"Corrections update the game record and derived statistics. The career journal keeps previously published stories and decisions.":"Korrekturen aktualisieren den Spieleintrag und berechnete Statistiken. Bereits veröffentlichte Geschichten und Entscheidungen bleiben in der Chronik."}</p>}
 <form ref={formRef} onSubmit={submit}><fieldset disabled={lock}><legend className="srOnly">{en?"Game result and player statistics":"Spielergebnis und Spielerstatistik"}</legend><div className="grid2"><label>{game.away?.abbreviation} · {en?"Away score":"Auswärtspunkte"}<input name="awayScore" type="number" min="0" max="9999" required defaultValue={existingResult?.away_score??""}/></label><label>{game.home?.abbreviation} · {en?"Home score":"Heimpunkte"}<input name="homeScore" type="number" min="0" max="9999" required defaultValue={existingResult?.home_score??""}/></label></div><label>{en?"Appearance":"Einsatz"}<select name="appearanceStatus" value={status} onChange={e=>setStatus(e.target.value)}><option value="played">{en?"Played":"Gespielt"}</option><option value="dnp_injury">{en?"DNP – injury":"DNP – Verletzung"}</option><option value="dnp_coach">{en?"DNP – coach decision":"DNP – Trainerentscheidung"}</option><option value="suspended">{en?"Suspended":"Gesperrt"}</option><option value="inactive">{en?"Inactive":"Inaktiv"}</option></select></label>
 {status!=="played"&&<StatusMessage tone="info">{en?"No appearance: production values are saved as zero and excluded from per-game averages. Describe an ejection or injury below.":"Ohne Einsatz werden Leistungswerte mit null gespeichert und nicht in die Durchschnitte eingerechnet. Einen Platzverweis oder eine Verletzung kannst du unten festhalten."}</StatusMessage>}
 <fieldset disabled={status!=="played"}><legend>{en?"Your stat line":"Deine Statline"}</legend><div className="statInputs">{statKeys.map(k=><label key={k}>{statLabels[k]}<input name={k} type="number" min={k==="plus_minus"?-9999:0} step={k==="minutes"?"0.1":"1"} required={status==="played"} defaultValue={existingStat?.[k]??0}/></label>)}</div></fieldset><div className="checks"><label><input type="checkbox" name="started" disabled={status!=="played"} defaultChecked={Boolean(existingStat?.started)}/> Starter</label><label><input type="checkbox" name="fouledOut" disabled={status!=="played"} defaultChecked={Boolean(existingStat?.fouled_out)}/> {en?"Fouled out":"Ausgefoult"}</label><label><input type="checkbox" name="ejected" defaultChecked={Boolean(existingStat?.ejected)}/> {en?"Ejected":"Platzverweis"}</label><label><input type="checkbox" name="injured" defaultChecked={Boolean(existingStat?.injured)}/> {en?"Injured":"Verletzt"}</label></div>
 <label>{en?"Injury or status note":"Verletzung oder Statusnotiz"}<textarea name="injuryNote" maxLength={2000} defaultValue={prose(existingStat,"injury_note",language)}/></label><label>{en?"Your game notes":"Deine Spielnotizen"}<textarea name="storyNotes" maxLength={12000} defaultValue={prose(existingStat||existingResult,"story_notes",language)} placeholder={en?"The run in the fourth. The defensive adjustment. The moment that mattered.":"Der Lauf im vierten Viertel. Die defensive Anpassung. Der entscheidende Moment."}/></label><label>{en?"Other notable players":"Weitere auffällige Spieler"}<textarea name="notables" maxLength={12000} defaultValue={existingNotables.filter(x=>!x.notes_language||x.notes_language===language).map(x=>`${x.player_name} | ${x.team_abbreviation} | ${x.note}`).join("\n")} placeholder={en?"One player per line: Name | Team | Note":"Eine Zeile je Spieler: Name | Team | Notiz"}/></label>
 {!editing&&<label className="checkRow"><input type="checkbox" name="autoMedia" defaultChecked={autoMedia}/> {en?"Generate reports and social reactions after saving":"Nach dem Speichern Berichte und Social-Reaktionen erzeugen"}</label>}{review&&<label className="checkRow"><input type="checkbox" required/> {en?"I checked the imported values against the image.":"Ich habe die übernommenen Werte mit dem Bild abgeglichen."}</label>}<button disabled={lock}>{busy?(en?"Saving…":"Speichere…"):editing?(en?"Save correction":"Korrektur speichern"):(en?"Save final score & stats":"Endstand & Stats speichern")}</button></fieldset></form></section>;
}
