"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import DraftFields from "@/components/DraftFields";
import TeamBadge from "@/components/TeamBadge";
import StatusMessage from "@/components/StatusMessage";
import {label} from "@/lib/labels";
export default function UniverseManager({universes,legacy,teams,season,language}:{universes:any[];legacy:any[];teams:any[];season:any;language:"de"|"en"}){
 const en=language==="en",router=useRouter();const [busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function run(path:string,body:any,open=false){if(busy)return;setBusy(true);setMsg("");try{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);if(open)location.assign("/");else router.refresh();}catch(e){setMsg(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div className="universeManager">{msg&&<StatusMessage tone="error">{msg}</StatusMessage>}<div className="universeList">{universes.map(u=>{const c=Array.isArray(u.career_profiles)?u.career_profiles[0]:u.career_profiles;return <article className="universeRow" key={u.id}><TeamBadge team={c?.current_team}/><div><small>{label(u.visibility,language)} · {u.language==="en"?"EN":"DE"}</small><h2>{u.name}</h2><p>{c?.player_name||"—"} · {c?.position||"—"} · OVR {c?.overall??"—"}</p><small>{u.universe_date}</small></div><div className="universeActions"><button disabled={busy} onClick={()=>run("/api/universes/select",{universeId:u.id},true)}>{en?"Open career":"Karriere öffnen"} →</button><button className="secondaryButton" disabled={busy} onClick={()=>run("/api/universes/visibility",{universeId:u.id,visibility:u.visibility==="public"?"private":"public"})}>{u.visibility==="public"?(en?"Make private":"Privat stellen"):(en?"Share publicly":"Öffentlich teilen")}</button>{u.visibility==="public"&&<a href={`/share/${u.slug}`} target="_blank" rel="noreferrer">{en?"Public career page":"Öffentliche Karriereseite"} ↗</a>}</div></article>})}</div>{!universes.length&&<p className="emptyState">{en?"Your first career starts here.":"Hier beginnt deine erste Karriere."}</p>}
 {legacy.length>0&&<details className="formDisclosure"><summary>{en?"Claim an existing career":"Bestehende Karriere übernehmen"}</summary><p>{en?"Use the previous admin password to claim your original career.":"Mit dem bisherigen Admin-Passwort kannst du deine ursprüngliche Karriere übernehmen."}</p>{legacy.map(u=><form key={u.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run("/api/universes/claim",{universeId:u.id,legacyPassword:f.get("legacyPassword")},true);}}><h3>{u.name}</h3><label>{en?"Previous admin password":"Bisheriges Admin-Passwort"}<input type="password" name="legacyPassword" required autoComplete="off"/></label><button disabled={busy}>{en?"Claim career":"Karriere übernehmen"}</button></form>)}</details>}
 <section className="newUniverse"><h2>{en?"A new name on the roster":"Ein neuer Name im Kader"}</h2><p>{en?"Create an independent MyNBA career. You control the player; every game builds the journal.":"Erstelle eine eigenständige MyNBA-Karriere. Du steuerst den Spieler; jedes Spiel schreibt die Chronik weiter."}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run("/api/universes/create",Object.fromEntries(f),true);}}><fieldset disabled={busy}><div className="grid2"><label>{en?"Career name":"Karrierename"}<input name="name" maxLength={100} placeholder={en?"My rookie season":"Meine Rookie-Saison"} required/></label><label>{en?"Player name":"Spielername"}<input name="playerName" maxLength={100} required/></label></div><div className="grid3"><label>Team<select name="teamId" required>{teams.map(t=><option key={t.id} value={t.id}>{t.abbreviation} · {t.city} {t.name}</option>)}</select></label><label>Position<input name="position" defaultValue="SG/SF" maxLength={20}/></label><label>OVR<input name="overall" type="number" min="25" max="99" defaultValue="75" required/></label></div><div className="grid3"><label>{en?"Jersey number":"Trikotnummer"}<input name="jerseyNumber" type="number" min="0" max="99"/></label></div><DraftFields language={language} career={{draft_year:season?.start_date?Number(season.start_date.slice(0,4)):null}}/><div className="grid2"><label>{en?"Start date":"Startdatum"}<input name="universeDate" type="date" defaultValue={season?.start_date||""} required/></label><label>{en?"Career language":"Karrieresprache"}<select name="language" defaultValue={language}><option value="de">{en?"German":"Deutsch"}</option><option value="en">{en?"English":"Englisch"}</option></select></label></div><button disabled={busy}>{busy?(en?"Creating…":"Wird erstellt…"):(en?"Begin career":"Karriere beginnen")}</button></fieldset></form></section></div>;
}
