import {InputError,validDate,cleanText} from "./game-input";

export type FootballMode="player"|"manager";
export type PlayerLine={appearance:"played"|"bench"|"injured"|"suspended";minutes:number|null;goals:number;assists:number;rating:number|null;shots:number|null;shots_on_target:number|null;passes:number|null;pass_accuracy:number|null;tackles:number|null;interceptions:number|null;saves:number|null;yellow_cards:number;red_cards:number};
export type FootballMatch={id:string;universe_id:string;season_id:string;match_date:string;competition:string;stage:string;round:number|null;home_club:string;away_club:string;tracked_club:string;status:"scheduled"|"completed";home_score:number|null;away_score:number|null;home_penalties:number|null;away_penalties:number|null;extra_time:boolean;player_stats:PlayerLine|null;possession:number|null;shots:number|null;shots_on_target:number|null;xg:number|null;notes:string|null;scorers:unknown[];updated_at:string};
export const formations={"4-2-3-1":["TW","LV","IV","IV","RV","ZDM","ZDM","LM","ZOM","RM","ST"],"4-3-3":["TW","LV","IV","IV","RV","ZM","ZDM","ZM","LF","ST","RF"],"4-4-2":["TW","LV","IV","IV","RV","LM","ZM","ZM","RM","ST","ST"],"3-5-2":["TW","IV","IV","IV","LM","ZM","ZDM","ZM","RM","ST","ST"],"4-5-1":["TW","LV","IV","IV","RV","LM","ZM","ZDM","ZM","RM","ST"]} as const;
export const positions=["TW","LV","IV","RV","LAV","RAV","ZDM","ZM","ZOM","LM","RM","LF","RF","ST"];
export function footballText(v:unknown,max=100,required=true){const s=cleanText(v,max);if(required&&!s)throw new InputError("MISSING_VALUES");return s||"";}
export function footballNumber(v:unknown,min=0,max=999,integer=true,optional=false):number|null{if(v==null||v===""){if(optional)return null;throw new InputError("MISSING_VALUES");}const n=Number(v);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw new InputError("INVALID_VALUES");return n;}
export function optionalDay(v:unknown){return v==null||v===""?null:validDate(v);}
export function clubsFromText(v:unknown):string[]{const clubs=String(v||"").split(/[\n;]+/).map(s=>s.trim()).filter(Boolean);if(clubs.length<2||clubs.length>40||clubs.some(s=>s.length>100)||new Set(clubs.map(s=>s.toLocaleLowerCase())).size!==clubs.length)throw new InputError("INVALID_FC_CLUBS");return clubs;}
export function parseFootballCreate(b:Record<string,unknown>){
 if(b.mode!=="player"&&b.mode!=="manager")throw new InputError("INVALID_FC_MODE");
 const start=validDate(b.universe_date),end=validDate(b.end_date);if(end<=start)throw new InputError("INVALID_SEASON");
 const club=footballText(b.club_name),clubs=String(b.clubs||"").trim()?clubsFromText(b.clubs):[club];if(!clubs.includes(club))throw new InputError("INVALID_FC_CLUBS");
 const color=String(b.club_color||"#28684b");if(!/^#[0-9a-f]{6}$/i.test(color))throw new InputError("INVALID_VALUES");
 const formation=String(b.formation||"4-2-3-1");if(!(formation in formations))throw new InputError("INVALID_LINEUP");
 return {name:footballText(b.name),mode:b.mode,person_name:footballText(b.person_name),club_name:club,club_code:footballText(b.club_code,8,false)||null,club_color:color,league:footballText(b.league),position:footballText(b.position||"ST",12),overall:footballNumber(b.overall??75,1,99),jersey_number:footballNumber(b.jersey_number,1,99,true,true),nationality:footballText(b.nationality,80,false)||null,birth_date:optionalDay(b.birth_date),formation,budget:footballNumber(b.budget??0,0,1e12,false),weekly_wage:footballNumber(b.weekly_wage??0,0,1e9,false),contract_until:optionalDay(b.contract_until),universe_date:start,end_date:end,season_name:footballText(b.season_name,40),language:b.language==="en"?"en":"de",clubs};
}
export function parseFootballMatch(b:Record<string,any>,mode:FootballMode):Omit<FootballMatch,"id"|"universe_id"|"updated_at">{
 const status=b.status;if(status!=="scheduled"&&status!=="completed")throw new InputError("INVALID_STATUS");
 const home=footballText(b.home_club),away=footballText(b.away_club),tracked=footballText(b.tracked_club);if(home.toLowerCase()===away.toLowerCase())throw new InputError("INVALID_FC_MATCH");
 const completed=status==="completed",hs=completed?footballNumber(b.home_score,0,99):null,as=completed?footballNumber(b.away_score,0,99):null;
 const hp=completed?footballNumber(b.home_penalties,0,99,true,true):null,ap=completed?footballNumber(b.away_penalties,0,99,true,true):null;
 const stage=footballText(b.stage||"league",40),extra=Boolean(b.extra_time);if((hp==null)!==(ap==null)||(hp!=null&&(hs!==as||hp===ap||stage==="league"||stage==="friendly"))||(extra&&stage==="league"))throw new InputError("INVALID_FC_MATCH");
 let player_stats:PlayerLine|null=null;
 if(completed&&mode==="player"&&[home,away].includes(tracked)){
  const s=b.player_stats||{},appearance=s.appearance||"played";if(!["played","bench","injured","suspended"].includes(appearance))throw new InputError("INVALID_STATUS");const played=appearance==="played";
  const stat=(key:string,max=999,integer=true)=>played?footballNumber(s[key],0,max,integer,true):null;
  player_stats={appearance,minutes:stat("minutes",extra?120:90),goals:played?Number(footballNumber(s.goals??0,0,99)):0,assists:played?Number(footballNumber(s.assists??0,0,99)):0,rating:stat("rating",10,false),shots:stat("shots"),shots_on_target:stat("shots_on_target"),passes:stat("passes"),pass_accuracy:stat("pass_accuracy",100,false),tackles:stat("tackles"),interceptions:stat("interceptions"),saves:stat("saves"),yellow_cards:played?Number(footballNumber(s.yellow_cards??0,0,2)):0,red_cards:played?Number(footballNumber(s.red_cards??0,0,1)):0};
  const score=home===tracked?hs!:as!;if(player_stats.goals+player_stats.assists>score)throw new InputError("INVALID_FC_STATS");
  if(player_stats.shots!=null&&player_stats.shots_on_target!=null&&player_stats.shots_on_target>player_stats.shots)throw new InputError("INVALID_FC_STATS");
 }
 const shots=footballNumber(b.shots,0,999,true,true),target=footballNumber(b.shots_on_target,0,999,true,true);if(shots!=null&&target!=null&&target>shots)throw new InputError("INVALID_FC_STATS");
 return {season_id:footballText(b.season_id,36),match_date:validDate(b.match_date),competition:footballText(b.competition),stage,round:footballNumber(b.round,1,1000,true,true),home_club:home,away_club:away,tracked_club:tracked,status,home_score:hs,away_score:as,home_penalties:hp,away_penalties:ap,extra_time:completed&&extra,player_stats,possession:footballNumber(b.possession,0,100,false,true),shots,shots_on_target:target,xg:footballNumber(b.xg,0,99,false,true),notes:footballText(b.notes,6000,false)||null,scorers:[]};
}
export function matchResult(m:Pick<FootballMatch,"status"|"home_score"|"away_score"|"home_penalties"|"away_penalties"|"home_club"|"away_club"|"tracked_club">):"W"|"D"|"L"|null{if(m.status!=="completed"||m.home_score==null||m.away_score==null||![m.home_club,m.away_club].includes(m.tracked_club))return null;let h=m.home_score,a=m.away_score;if(h===a&&m.home_penalties!=null&&m.away_penalties!=null){h=m.home_penalties;a=m.away_penalties;}const mine=m.tracked_club===m.home_club?h:a,opp=m.tracked_club===m.home_club?a:h;return mine===opp?"D":mine>opp?"W":"L";}
export function footballSummary(matches:FootballMatch[]){const tracked=matches.filter(m=>matchResult(m)!=null),played=tracked.filter(m=>m.player_stats?.appearance==="played"),ratings=played.flatMap(m=>m.player_stats?.rating==null?[]:[Number(m.player_stats.rating)]);const sum=(key:"goals"|"assists"|"saves"|"minutes")=>played.reduce((v,m)=>v+(Number(m.player_stats?.[key])||0),0);const gf=tracked.reduce((v,m)=>v+Number(m.tracked_club===m.home_club?m.home_score:m.away_score),0),ga=tracked.reduce((v,m)=>v+Number(m.tracked_club===m.home_club?m.away_score:m.home_score),0);return {matches:tracked.length,appearances:played.length,wins:tracked.filter(m=>matchResult(m)==="W").length,draws:tracked.filter(m=>matchResult(m)==="D").length,losses:tracked.filter(m=>matchResult(m)==="L").length,goals:sum("goals"),assists:sum("assists"),saves:sum("saves"),minutes:sum("minutes"),rating:ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null,goalsFor:gf,goalsAgainst:ga,cleanSheets:tracked.filter(m=>(m.tracked_club===m.home_club?m.away_score:m.home_score)===0).length,hatTricks:played.filter(m=>Number(m.player_stats?.goals)>=3).length,brace:played.filter(m=>Number(m.player_stats?.goals)>=2).length,bestGoals:Math.max(0,...played.map(m=>Number(m.player_stats?.goals)||0)),bestRating:ratings.length?Math.max(...ratings):null};}
export function footballTable(matches:FootballMatch[],clubs:string[],league:string){const rows=new Map(clubs.map(name=>[name,{name,played:0,w:0,d:0,l:0,gf:0,ga:0,points:0}]));for(const m of matches){if(m.status!=="completed"||m.stage!=="league"||m.competition!==league||m.home_score==null||m.away_score==null)continue;for(const [club,gf,ga] of [[m.home_club,m.home_score,m.away_score],[m.away_club,m.away_score,m.home_score]] as [string,number,number][]){const r=rows.get(club)||{name:club,played:0,w:0,d:0,l:0,gf:0,ga:0,points:0};r.played++;r.gf+=gf;r.ga+=ga;if(gf>ga){r.w++;r.points+=3;}else if(gf===ga){r.d++;r.points++;}else r.l++;rows.set(club,r);}}return [...rows.values()].sort((a,b)=>b.points-a.points||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.name.localeCompare(b.name));}
export function generateFootballSchedule(clubs:string[],start:string,end:string,league:string,tracked:string){clubsFromText(clubs.join("\n"));const first=Date.parse(validDate(start)+"T12:00:00Z"),last=Date.parse(validDate(end)+"T12:00:00Z");if(last<=first)throw new InputError("INVALID_SEASON");const wheel:(string|null)[]=[...clubs];if(wheel.length%2)wheel.push(null);const rounds=wheel.length-1,fixtures:{match_date:string;competition:string;round:number;home_club:string;away_club:string;tracked_club:string}[]=[];for(let r=0;r<rounds;r++){for(let i=0;i<wheel.length/2;i++){let h=wheel[i],a=wheel[wheel.length-1-i];if(!h||!a)continue;if((r+i)%2)[h,a]=[a,h];for(let leg=0;leg<2;leg++){const round=r+leg*rounds;fixtures.push({match_date:new Date(first+(last-first)*round/Math.max(1,2*rounds-1)).toISOString().slice(0,10),competition:league,round:round+1,home_club:leg?a:h,away_club:leg?h:a,tracked_club:tracked});}}wheel.splice(1,0,wheel.pop()!);}return fixtures.sort((a,b)=>a.round-b.round||a.home_club.localeCompare(b.home_club));}
