import {findFootballClub,findFootballLeague} from "./football-catalog";
export type FootballOutlet={name:string;url:string;country:string;broadcast?:boolean};
const regional:Record<string,[string,string,boolean?][]>= {
 Deutschland:[["kicker","https://www.kicker.de"],["Sky Sport Deutschland","https://sport.sky.de",true],["Sportschau","https://www.sportschau.de",true],["SPORT1","https://www.sport1.de"],["BILD Sport","https://www.bild.de/sport"]],
 England:[["BBC Sport","https://www.bbc.com/sport/football"],["Sky Sports","https://www.skysports.com/football",true],["The Guardian Football","https://www.theguardian.com/football"],["The Athletic","https://www.nytimes.com/athletic/football"],["talkSPORT","https://talksport.com/football"]],
 Frankreich:[["L’Équipe","https://www.lequipe.fr"],["RMC Sport","https://rmcsport.bfmtv.com",true],["Franceinfo Sport","https://www.franceinfo.fr/sports"],["Eurosport France","https://www.eurosport.fr"],["Le Parisien Sport","https://www.leparisien.fr/sports"]],
 Italien:[["La Gazzetta dello Sport","https://www.gazzetta.it"],["Sky Sport Italia","https://sport.sky.it/calcio",true],["Corriere dello Sport","https://www.corrieredellosport.it"],["Tuttosport","https://www.tuttosport.com"],["Sport Mediaset","https://www.sportmediaset.mediaset.it"]],
 Spanien:[["MARCA","https://www.marca.com"],["AS","https://as.com"],["Movistar Plus+","https://www.movistarplus.es/deportes",true],["Mundo Deportivo","https://www.mundodeportivo.com"],["SPORT","https://www.sport.es"]],
 Niederlande:[["Voetbal International","https://www.vi.nl"],["ESPN Nederland","https://www.espn.nl",true],["NOS Sport","https://nos.nl/sport"],["De Telegraaf Telesport","https://www.telegraaf.nl/sport"]],
 Portugal:[["A Bola","https://www.abola.pt"],["SPORT TV","https://www.sporttv.pt",true],["Record","https://www.record.pt"],["O Jogo","https://www.ojogo.pt"]],
 Belgien:[["Sporza","https://sporza.be",true],["RTBF Sport","https://www.rtbf.be/sport"],["DH Les Sports+","https://www.dhnet.be/sports"],["Het Nieuwsblad Sport","https://www.nieuwsblad.be/sport"]],
 Schottland:[["BBC Sport Scotland","https://www.bbc.com/sport/scotland"],["Sky Sports","https://www.skysports.com/football",true],["The Scotsman Sport","https://www.scotsman.com/sport"],["Daily Record Sport","https://www.dailyrecord.co.uk/sport"]],
 Österreich:[["LAOLA1","https://www.laola1.at"],["Sky Sport Austria","https://www.skysportaustria.at",true],["ORF Sport","https://sport.orf.at"],["Kurier Sport","https://kurier.at/sport"]],
 Schweiz:[["Blick Sport","https://www.blick.ch/sport"],["SRF Sport","https://www.srf.ch/sport",true],["blue Sport","https://www.bluewin.ch/de/sport"],["Watson Sport","https://www.watson.ch/sport"]],
 Dänemark:[["Tipsbladet","https://www.tipsbladet.dk"],["TV 2 Sport","https://sport.tv2.dk",true],["bold.dk","https://bold.dk"],["DR Sport","https://www.dr.dk/sporten"]],
 Norwegen:[["VG Sport","https://www.vg.no/sport"],["TV 2 Norge Sport","https://www.tv2.no/sport",true],["NRK Sport","https://www.nrk.no/sport"],["Dagbladet Sport","https://www.dagbladet.no/sport"]],
 Schweden:[["Aftonbladet Sportbladet","https://www.aftonbladet.se/sportbladet"],["SVT Sport","https://www.svt.se/sport",true],["Expressen Sport","https://www.expressen.se/sport"],["Fotbollskanalen","https://www.fotbollskanalen.se"]],
 Polen:[["Przegląd Sportowy Onet","https://przegladsportowy.onet.pl"],["Polsat Sport","https://www.polsatsport.pl",true],["TVP Sport","https://sport.tvp.pl"],["CANAL+ Sport Polska","https://www.canalplus.com/pl/sport"]],
 Rumänien:[["Gazeta Sporturilor","https://www.gsp.ro"],["Digi Sport","https://www.digisport.ro",true],["ProSport","https://www.prosport.ro"],["Sport.ro","https://www.sport.ro"]],
 Türkei:[["Fanatik","https://www.fanatik.com.tr"],["beIN SPORTS Türkiye","https://beinsports.com.tr",true],["TRT Spor","https://www.trtspor.com.tr"],["Fotomaç","https://www.fotomac.com.tr"]],
 Irland:[["The42","https://www.the42.ie"],["RTÉ Sport","https://www.rte.ie/sport",true],["Irish Independent Sport","https://www.independent.ie/sport"],["Irish Times Sport","https://www.irishtimes.com/sport"]],
 China:[["Sina Sports","https://sports.sina.com.cn"],["CCTV Sport","https://sports.cctv.com",true],["Tencent Sports","https://sports.qq.com"],["NetEase Sports","https://sports.163.com"]],
 Südkorea:[["Naver Sports","https://sports.naver.com"],["SPOTV","https://www.spotv.net",true],["Sports Chosun","https://sports.chosun.com"],["Ilgan Sports","https://isplus.com"]],
 Indien:[["Sportstar","https://sportstar.thehindu.com"],["ESPN India","https://www.espn.in",true],["Indian Express Sports","https://indianexpress.com/section/sports"],["The Times of India Sports","https://timesofindia.indiatimes.com/sports"]],
 "Saudi-Arabien":[["Arriyadiyah","https://arriyadiyah.com"],["SSC Sports","https://ssc.tv",true],["Asharq Al-Awsat Sport","https://aawsat.com"],["Arab News Sport","https://www.arabnews.com/sport"]],
 "Australien / Neuseeland":[["ABC Sport","https://www.abc.net.au/news/sport"],["FOX Sports Australia","https://www.foxsports.com.au/football",true],["SBS Sport","https://www.sbs.com.au/sport"],["Stuff Sport","https://www.stuff.co.nz/sport"]],
 "USA / Kanada":[["ESPN","https://www.espn.com/soccer"],["CBS Sports","https://www.cbssports.com/soccer",true],["FOX Sports","https://www.foxsports.com/soccer"],["TSN","https://www.tsn.ca/soccer"],["The Athletic","https://www.nytimes.com/athletic/football"]],
 Mexiko:[["Récord","https://www.record.com.mx"],["TUDN","https://www.tudn.com/futbol",true],["ESPN México","https://www.espn.com.mx/futbol"],["Mediotiempo","https://www.mediotiempo.com"]],
 Argentinien:[["Olé","https://www.ole.com.ar"],["TyC Sports","https://www.tycsports.com",true],["ESPN Argentina","https://www.espn.com.ar/futbol"],["TNT Sports Argentina","https://tntsports.com.ar"]],
 Brasilien:[["ge.globo","https://ge.globo.com"],["ESPN Brasil","https://www.espn.com.br/futebol",true],["Lance!","https://www.lance.com.br"],["TNT Sports Brasil","https://tntsports.com.br"]],
};
export const internationalFootballOutlets:FootballOutlet[]=[{name:"BBC Sport",url:"https://www.bbc.com/sport/football",country:"International"},{name:"ESPN",url:"https://www.espn.com/soccer",country:"International"},{name:"Sky Sports",url:"https://www.skysports.com/football",country:"International",broadcast:true},{name:"The Athletic",url:"https://www.nytimes.com/athletic/football",country:"International"},{name:"Reuters Sports",url:"https://www.reuters.com/sports",country:"International"}];
export const footballOutlets:FootballOutlet[]=Object.entries(regional).flatMap(([country,items])=>items.map(([name,url,broadcast])=>({name,url,country,broadcast})));
export function footballMediaCountry(club:string,league?:string){const team=findFootballClub(club,league),selected=findFootballLeague(league||"");const country=selected?.kind==="league"?selected.country:team?.country||"International";return country==="USA"||country==="Kanada"?"USA / Kanada":country==="Australien"||country==="Neuseeland"?"Australien / Neuseeland":country;}
export function outletsForFootballCountry(country:string){return footballOutlets.filter(outlet=>outlet.country===country).length?footballOutlets.filter(outlet=>outlet.country===country):internationalFootballOutlets;}
