import {footballSummary,matchResult,type FootballMatch} from "./football";
import {footballMediaCountry,outletsForFootballCountry,internationalFootballOutlets,type FootballOutlet} from "./football-outlets";
export const footballMediaVersion=2;
export const footballMediaKinds=["recap","broadcast","analysis","local","international","statistics","critical","fan","social"] as const;
export type FootballMediaKind=typeof footballMediaKinds[number];
export type FootballMediaPlan={kind:FootballMediaKind;outlet:FootballOutlet|null;author:string;focus:string;style:string;words:[number,number]};
export function footballMediaSeed(value:string){let seed=2166136261;for(let i=0;i<value.length;i++){seed^=value.charCodeAt(i);seed=Math.imul(seed,16777619);}return seed>>>0;}
export function buildFootballMediaContext(m:FootballMatch,p:any,history:FootballMatch[]){
 const completed=history.filter(x=>x.status==="completed"&&x.season_id===m.season_id&&x.match_date<=m.match_date),prior=completed.filter(x=>x.id!==m.id&&x.match_date<m.match_date&&matchResult(x)!=null).sort((a,b)=>b.match_date.localeCompare(a.match_date)).slice(0,5);
 const historicalProfile={person_name:p.person_name,club_name:m.tracked_club,mode:p.mode,position:p.position,league:p.league},mine=m.home_club===m.tracked_club?m.home_score:m.away_score,against=m.home_club===m.tracked_club?m.away_score:m.home_score;
 const country=footballMediaCountry(m.tracked_club,p.league),opponent=m.home_club===m.tracked_club?m.away_club:m.home_club;
 return {profile:historicalProfile,match:m,result:matchResult(m),ownScore:mine,opponentScore:against,opponent,country,opponentCountry:footballMediaCountry(opponent),summary:footballSummary(completed),previousResults:prior.map(x=>({date:x.match_date,competition:x.competition,result:matchResult(x),score:`${x.home_score}:${x.away_score}`,club:x.tracked_club})),form:prior.map(x=>matchResult(x)).reverse().join(""),seed:footballMediaSeed(`${m.id}|${m.updated_at}|${m.competition}|${m.home_score}:${m.away_score}`)};
}
export function footballMediaPlan(context:ReturnType<typeof buildFootballMediaContext>,recent:{outlet?:string|null;headline?:string;body?:string}[]=[]):FootballMediaPlan[]{
 context={...context,seed:footballMediaSeed(`${context.seed}|${recent.map(x=>x.headline||"").join("|")}`)};
 const regional=outletsForFootballCountry(context.country),opposition=outletsForFootballCountry(context.opponentCountry),used=new Set<string>(),previous=new Set(recent.slice(0,9).map(x=>x.outlet));
 function pick(pool:FootballOutlet[],offset:number){const options=pool.filter(outlet=>!used.has(outlet.name)),fresh=options.filter(outlet=>!previous.has(outlet.name)),choices=fresh.length?fresh:options.length?options:internationalFootballOutlets.filter(outlet=>!used.has(outlet.name));const chosen=choices[(context.seed+offset)%choices.length]||pool[offset%pool.length];used.add(chosen.name);return chosen;}
 const lenses={recap:["result, competition and what it changes for this career","neutral newspaper report"],broadcast:["individual impact and one clearly supported strength or weakness","concise television pundit analysis"],analysis:["available match statistics; explain their limits without inventing tactics","specialist football analysis"],local:["tracked club and its supporters' sporting expectations based on recorded form","local club newspaper"],international:["opponent and competition from an outside perspective","international football desk"],statistics:["season totals, recent results and one concrete comparison with this performance","data desk with precise numbers"],critical:["one grounded reservation; balanced praise after a strong match, fair criticism after a weak one","skeptical but fair columnist"],fan:["emotion about this specific score or recorded personal contribution","fictional supporter post; spontaneous and opinionated"],social:["the single most striking recorded fact; a different focus from the fan post","short fictional social post; punchy but factual"]} as const;
 return footballMediaKinds.map((kind,i)=>{
  const outlet=kind==="fan"||kind==="social"?null:kind==="recap"?pick(regional.filter(o=>!o.broadcast).length?regional.filter(o=>!o.broadcast):regional,i):kind==="broadcast"?pick(regional.filter(o=>o.broadcast).length?regional.filter(o=>o.broadcast):internationalFootballOutlets.filter(o=>o.broadcast),i):kind==="international"?pick([...opposition,...internationalFootballOutlets],i):pick(regional,i);
  return {kind,outlet,author:kind==="fan"?["@Kurvenstimme","@AwayEndDiary","@ClubPulse","@NinetyPlusCrew"][context.seed%4]:kind==="social"?["@TouchlineDaily","@MatchLens","@FootballNotebook","@FinalWhistleFeed"][(context.seed+1)%4]:["Mara König","Jonas Vale","Alex Moreno","Lea Winter","Sam Rivera","Nina Laurent","Luca Voss"][(context.seed+i)%7],focus:lenses[kind][0],style:lenses[kind][1],words:kind==="fan"||kind==="social"?[15,40]:kind==="statistics"?[40,65]:[60,100]};
 });
}
