import {footballMediaKinds,footballMediaVersion,type FootballMediaPlan} from "./football-media-context";
export const footballMediaSchema={type:"object",additionalProperties:false,required:["items","interview"],properties:{items:{type:"array",minItems:9,maxItems:9,items:{type:"object",additionalProperties:false,required:["kind","headline","body"],properties:{kind:{type:"string",enum:footballMediaKinds},headline:{type:"string"},body:{type:"string"}}}},interview:{type:"object",additionalProperties:false,required:["question","options"],properties:{question:{type:"string"},options:{type:"array",minItems:3,maxItems:3,items:{type:"string"}}}}}};
const key=(s:string)=>s.toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim();
export function validateFootballMediaOutput(parsed:any,plan:FootballMediaPlan[],recent:{headline?:string;body?:string}[],model:string){
 if(!parsed||!Array.isArray(parsed.items)||parsed.items.length!==plan.length||new Set(parsed.items.map((x:any)=>x?.kind)).size!==plan.length)throw Error("AI_UNAVAILABLE");
 const headlines=new Set<string>(),bodies=new Set<string>(),oldHeadlines=new Set(recent.map(x=>key(x.headline||""))),oldBodies=new Set(recent.map(x=>key(x.body||"")));
 const items=plan.map(row=>{const item=parsed.items.find((x:any)=>x?.kind===row.kind);if(!item||typeof item.headline!=="string"||typeof item.body!=="string")throw Error("AI_UNAVAILABLE");const headline=item.headline.trim(),body=item.body.trim(),h=key(headline),b=key(body);if(headline.length<8||headline.length>300||body.length<(row.kind==="fan"||row.kind==="social"?15:180)||body.length>5000||headlines.has(h)||bodies.has(b)||oldHeadlines.has(h)||oldBodies.has(b))throw Error("AI_UNAVAILABLE");headlines.add(h);bodies.add(b);return {kind:row.kind,author:row.author,outlet:row.outlet?.name||null,headline,body,source:"openai" as const,generation_version:footballMediaVersion,model};});
 const interview=parsed.interview;if(!interview||typeof interview.question!=="string"||interview.question.trim().length<10||interview.question.length>600||!Array.isArray(interview.options)||interview.options.length!==3||interview.options.some((option:any)=>typeof option!=="string"||option.trim().length<4||option.length>300)||new Set(interview.options.map((option:string)=>key(option))).size!==3)throw Error("AI_UNAVAILABLE");
 return {items,interview:{question:interview.question.trim(),options:interview.options.map((option:string)=>option.trim())}};
}
