import {InputError,validDate} from "./game-input";
import {footballCompetitionStage,footballStages} from "./football-competitions";

export type FootballFieldIssue={field:string;code:string;message:[string,string]};
export type FootballFieldError={field:string;message:string};
export type FootballValidationContext={mode?:string;club?:string;currentDate?:string;budget?:number;formation?:string;position?:string};
export class FootballValidationError extends InputError{
 constructor(public issues:FootballFieldIssue[]){super(issues[0]?.code||"INVALID_VALUES");}
}
export function localizeFootballIssues(issues:FootballFieldIssue[],en=false):FootballFieldError[]{return issues.map(({field,message})=>({field,message:message[en?1:0]}));}
const names:Record<string,[string,string]>={
 name:["Name","Name"],mode:["Karrieremodus","Career mode"],person_name:["Spieler-/Trainername","Player/manager name"],club_name:["Verein","Club"],club_code:["Vereinskürzel","Club code"],club_color:["Vereinsfarbe","Club colour"],league:["Liga","League"],clubs:["Ligavereine","League clubs"],position:["Position","Position"],overall:["Gesamtwertung (OVR)","Overall (OVR)"],jersey_number:["Trikotnummer","Shirt number"],nationality:["Nationalität","Nationality"],birth_date:["Geburtsdatum","Date of birth"],formation:["Formation","Formation"],budget:["Transferbudget","Transfer budget"],weekly_wage:["Wochengehalt","Weekly wage"],contract_until:["Vertrag bis","Contract until"],universe_date:["Karrieredatum","Career date"],start_date:["Saisonbeginn","Season start"],end_date:["Saisonende","Season end"],season_name:["Saisonbezeichnung","Season name"],match_date:["Spieldatum","Match date"],competition:["Wettbewerb","Competition"],stage:["Spielart","Match type"],round:["Spieltag / Runde","Matchday / round"],home_club:["Heimverein","Home club"],away_club:["Gastverein","Away club"],status:["Status","Status"],home_score:["Tore Heim","Home goals"],away_score:["Tore Gast","Away goals"],home_penalties:["Elfmeterschießen Heim","Home shootout goals"],away_penalties:["Elfmeterschießen Gast","Away shootout goals"],extra_time:["Verlängerung","Extra time"],possession:["Ballbesitz","Possession"],shots:["Teamschüsse","Team shots"],shots_on_target:["Teamschüsse aufs Tor","Team shots on target"],xg:["xG","xG"],notes:["Notizen","Notes"],age:["Alter","Age"],role:["Kaderrolle","Squad role"],market_value:["Marktwert","Market value"],direction:["Transferart","Transfer direction"],kind:["Art","Type"],player_name:["Spielername","Player name"],from_club:["Abgebender Verein","From club"],to_club:["Neuer Verein","New club"],transfer_date:["Transferdatum","Transfer date"],fee:["Ablöse","Transfer fee"],squad_id:["Kaderspieler","Squad player"],award_date:["Auszeichnungsdatum","Award date"],season_id:["Saison","Season"],
 "stats.appearance":["Einsatzstatus","Appearance"],"stats.minutes":["Minuten inkl. Nachspielzeit","Minutes incl. stoppage time"],"stats.goals":["Spielertore","Player goals"],"stats.assists":["Assists","Assists"],"stats.rating":["Matchrating","Match rating"],"stats.yellow_cards":["Gelbe Karten","Yellow cards"],"stats.red_cards":["Rote Karten","Red cards"],"stats.shots":["Spielerschüsse","Player shots"],"stats.shots_on_target":["Spielerschüsse aufs Tor","Player shots on target"],"stats.passes":["Pässe","Passes"],"stats.pass_accuracy":["Passquote","Pass accuracy"],"stats.tackles":["Tackles","Tackles"],"stats.interceptions":["Abgefangene Bälle","Interceptions"],"stats.saves":["Paraden","Saves"],
};
export function footballIssue(field:string,de:string,en:string,code="INVALID_VALUES"):FootballFieldIssue{const label=names[field]||[field,field];return {field,code,message:[`${label[0]}: ${de}`,`${label[1]}: ${en}`]};}

// One collector is shared by the client and API: all invalid fields are reported together.
export function footballValidationIssues(action:string,b:Record<string,any>,ctx:FootballValidationContext={}):FootballFieldIssue[]{
 const issues:FootballFieldIssue[]=[],add=(field:string,de:string,en:string,code?:string)=>issues.push(footballIssue(field,de,en,code));
 const value=(field:string)=>field.startsWith("stats.")?b.player_stats?.[field.slice(6)]:b[field];
 const bad=(field:string)=>issues.some(issue=>issue.field===field);
 function text(field:string,max=100,required=true,fallback?:unknown){const v=value(field)??fallback;if(v==null||String(v).trim()===""){if(required)add(field,"Bitte ausfüllen.","This field is required.","MISSING_VALUES");return "";}if(typeof v!=="string"||v.length>max)add(field,`Bitte höchstens ${max} Zeichen eintragen.`,`Enter at most ${max} characters.`,"TEXT_TOO_LONG");return String(v).trim();}
 function number(field:string,min:number,max:number,integer=true,optional=false,fallback?:number){const v=value(field)??fallback;if(v==null||v===""){if(!optional)add(field,"Bitte eine Zahl eintragen.","Enter a number.","MISSING_VALUES");return null;}const n=Number(v);if(typeof v==="boolean"||!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))add(field,`${integer?"Ganze Zahl":"Zahl"} von ${min} bis ${max} erforderlich.${field==="stats.minutes"?" Nachspielzeit zählt mit; dafür ist kein Haken bei Verlängerung nötig.":""}`,`${integer?"Whole number":"Number"} from ${min} to ${max} required.${field==="stats.minutes"?" Include stoppage time; it does not require extra time to be checked.":""}`,field==="stats.minutes"?"INVALID_FC_MINUTES":"INVALID_VALUES");return bad(field)?null:n;}
 function day(field:string,optional=false){const v=value(field);if(optional&&(v==null||v===""))return null;try{return validDate(v);}catch{add(field,"Bitte ein gültiges Datum eintragen.","Enter a valid date.","INVALID_DATE");return null;}}
 function choice(field:string,options:readonly string[],fallback?:string){const v=value(field)??fallback;if(typeof v!=="string"||!options.includes(v))add(field,`Bitte eine gültige Auswahl treffen (${options.join(", ")}).`,`Choose a valid option (${options.join(", ")}).`,"INVALID_STATUS");return v;}
 function clubs(own:string,required=false){if(!required&&!String(b.clubs||"").trim())return;const list=String(b.clubs||"").split(/[\n;]+/).map(s=>s.trim()).filter(Boolean);if(list.length<2||list.length>40)add("clubs",`2 bis 40 Vereine erforderlich; eingetragen: ${list.length}.`,`2–40 clubs required; entered: ${list.length}.`,"INVALID_FC_CLUBS");const seen=new Set<string>(),duplicates:string[]=[];for(const club of list){const key=club.toLocaleLowerCase();if(seen.has(key))duplicates.push(club);seen.add(key);}if(duplicates.length)add("clubs",`Vereine doppelt eingetragen: ${[...new Set(duplicates)].join(", ")}.`,`Duplicate clubs: ${[...new Set(duplicates)].join(", ")}.`,"INVALID_FC_CLUBS");if(list.some(club=>club.length>100))add("clubs","Jeder Vereinsname darf höchstens 100 Zeichen haben.","Each club name can have at most 100 characters.","INVALID_FC_CLUBS");if(own&&!list.includes(own))add("clubs",`Dein Verein „${own}“ fehlt. Ergänze ihn genau mit diesem Namen.`,`Your club “${own}” is missing. Add it with this exact name.`,"INVALID_FC_CLUBS");}
 function person(){text("person_name");text("position",12,true,ctx.position||"ST");number("overall",1,99,true,false,action==="create"?75:undefined);number("jersey_number",1,99,true,true);text("nationality",80,false);day("birth_date",true);day("contract_until",true);number("budget",0,1e12,false,false,ctx.budget??0);number("weekly_wage",0,1e9,false,false,0);choice("formation",["4-2-3-1","4-3-3","4-4-2","3-5-2","4-5-1"],ctx.formation||"4-2-3-1");}
 if(action==="create"||action==="profile"){
  text("name");person();const start=day("universe_date");
  if(action==="create"){choice("mode",["player","manager"]);const own=text("club_name");text("club_code",8,false);text("league");text("season_name",40);clubs(own);if(b.club_color!=null&&!/^#[0-9a-f]{6}$/i.test(String(b.club_color)))add("club_color","Eine Farbe im Format #RRGGBB ist erforderlich.","Use a colour in #RRGGBB format.");const end=day("end_date");if(start&&end&&end<=start)add("end_date",`Muss nach dem Startdatum ${start} liegen.`,`Must be after the start date ${start}.`,"INVALID_SEASON");}
 }else if(action==="match"){
  day("match_date");text("season_id",36);const home=text("home_club"),away=text("away_club");text("competition");const stage=choice("stage",footballStages,"league"),status=choice("status",["scheduled","completed"]);number("round",1,1000,true,true);text("notes",6000,false);
  if(home&&away&&home.toLocaleLowerCase()===away.toLocaleLowerCase())add("away_club","Heim- und Gastverein müssen unterschiedlich sein.","Home and away clubs must be different.","INVALID_FC_MATCH");
  const expected=footballCompetitionStage(String(b.competition||""));if(expected&&expected!==stage)add("stage",`„${b.competition}“ gehört zur Spielart ${expected==="international"?"International":expected==="cup"?"Pokal":"Liga"}.`,`“${b.competition}” belongs to match type ${expected}.`,"INVALID_FC_MATCH");
  if(status==="completed"){
   const homeScore=number("home_score",0,99),awayScore=number("away_score",0,99),hp=number("home_penalties",0,99,true,true),ap=number("away_penalties",0,99,true,true);
   if(!bad("home_penalties")&&!bad("away_penalties")){
    if((hp===null)!==(ap===null))add(hp===null?"home_penalties":"away_penalties","Beim Elfmeterschießen fehlen die Treffer dieses Vereins.","Enter this club's shootout goals as well.","INVALID_FC_MATCH");
    if(hp!==null&&ap!==null){if(hp===ap)for(const field of ["home_penalties","away_penalties"])add(field,"Ein abgeschlossenes Elfmeterschießen braucht einen Sieger; beide Werte sind gleich.","A completed shootout needs a winner; the values are equal.","INVALID_FC_MATCH");if(homeScore!==null&&awayScore!==null&&homeScore!==awayScore)for(const field of ["home_penalties","away_penalties"])add(field,`Elfmeterschießen ist nur bei einem Unentschieden möglich; Endstand: ${homeScore}:${awayScore}.`,`A shootout requires a tied score; final score: ${homeScore}:${awayScore}.`,"INVALID_FC_MATCH");}
    if((hp!==null||ap!==null)&&(stage==="league"||stage==="friendly"))for(const field of ["home_penalties","away_penalties"])if(value(field)!==""&&value(field)!=null)add(field,"Bei Liga- oder Testspielen ist kein Elfmeterschießen vorgesehen. Prüfe die Spielart.","League and friendly matches do not use shootouts. Check the match type.","INVALID_FC_MATCH");
   }
   if(b.extra_time&&stage==="league")add("extra_time","Ligaspiele haben keine Verlängerung. Nachspielzeit wird bei den Minuten mitgezählt.","League matches do not have extra time. Include stoppage time in the minutes.","INVALID_FC_MATCH");
   const tracked=String(b.tracked_club||ctx.club||"");if(ctx.mode==="player"&&[home,away].includes(tracked)){
    const appearance=choice("stats.appearance",["played","bench","injured","suspended"],"played");if(appearance==="played"){
     number("stats.minutes",0,150,true,true);const goals=number("stats.goals",0,99,true,false,0),assists=number("stats.assists",0,99,true,false,0);number("stats.rating",0,10,false,true);number("stats.yellow_cards",0,2,true,false,0);number("stats.red_cards",0,1,true,false,0);
     for(const field of ["shots","shots_on_target","passes","tackles","interceptions","saves"])number(`stats.${field}`,0,999,true,true);number("stats.pass_accuracy",0,100,false,true);
     const score=home===tracked?homeScore:awayScore;if(score!==null&&goals!==null&&assists!==null&&goals+assists>score)for(const field of ["stats.goals","stats.assists"])add(field,`Tore (${goals}) + Assists (${assists}) = ${goals+assists}; dein Verein hat nur ${score} Tore erzielt.`,`Goals (${goals}) + assists (${assists}) = ${goals+assists}; your club scored only ${score} goals.`,"INVALID_FC_STATS");
     if(!bad("stats.shots")&&!bad("stats.shots_on_target")&&value("stats.shots")!=null&&value("stats.shots")!==""&&value("stats.shots_on_target")!=null&&value("stats.shots_on_target")!==""&&Number(value("stats.shots_on_target"))>Number(value("stats.shots")))add("stats.shots_on_target",`Darf die Spielerschüsse (${value("stats.shots")}) nicht überschreiten.`,`Cannot exceed player shots (${value("stats.shots")}).`,"INVALID_FC_STATS");
    }
   }
  }
  number("possession",0,100,false,true);number("xg",0,99,false,true);const shots=number("shots",0,999,true,true),target=number("shots_on_target",0,999,true,true);if(shots!==null&&target!==null&&target>shots)add("shots_on_target",`Darf die Teamschüsse (${shots}) nicht überschreiten.`,`Cannot exceed team shots (${shots}).`,"INVALID_FC_STATS");
 }else if(action==="season"){
  text("name",40);text("league");clubs(ctx.club||"");const start=day("start_date"),end=day("end_date");if(start&&ctx.currentDate&&start<=ctx.currentDate)add("start_date",`Muss nach dem aktuellen Karrieredatum ${ctx.currentDate} liegen.`,`Must be after your current career date ${ctx.currentDate}.`,"INVALID_SEASON");if(start&&end&&end<=start)add("end_date",`Muss nach dem Saisonbeginn ${start} liegen.`,`Must be after the season start ${start}.`,"INVALID_SEASON");
 }else if(action==="schedule"){clubs(ctx.club||"",true);
 }else if(action==="squad"){
  text("name");choice("position",["TW","LV","IV","RV","LAV","RAV","ZDM","ZM","ZOM","LM","RM","LF","RF","ST"]);number("overall",1,99);number("age",14,65,true,true);number("jersey_number",1,99,true,true);text("nationality",80,false);number("market_value",0,1e12,false,false,0);number("weekly_wage",0,1e9,false,false,0);day("contract_until",true);choice("status",["available","injured","suspended","loaned","departed"],"available");choice("role",["key","starter","rotation","prospect"],"rotation");text("notes",2000,false);
 }else if(action==="transfer"){
  const direction=choice("direction",["in","out","career"]),kind=choice("kind",["permanent","loan","free","return","manager"]);if(ctx.mode==="player"&&direction!=="career")add("direction","In der Spielerkarriere ist nur dein eigener Vereinswechsel möglich.","Player careers only support your own club change.","INVALID_TRANSFER");if(direction!=="career")text("player_name");const other=direction==="in"?"from_club":"to_club",club=text(other);if(club&&ctx.club&&club.toLocaleLowerCase()===ctx.club.toLocaleLowerCase())add(other,`Muss sich von deinem bisherigen Verein „${ctx.club}“ unterscheiden.`,`Must differ from your current club “${ctx.club}”.`,"INVALID_TRANSFER");const date=day("transfer_date");if(direction==="career"&&date&&ctx.currentDate&&date<ctx.currentDate)add("transfer_date",`Darf nicht vor dem Karrieredatum ${ctx.currentDate} liegen.`,`Cannot be before your career date ${ctx.currentDate}.`,"INVALID_TRANSFER");const fee=number("fee",0,1e12,false,false,0);if(direction==="in"&&fee!==null&&ctx.budget!=null&&fee>ctx.budget)add("fee",`Ablöse ${fee} € überschreitet dein Transferbudget von ${ctx.budget} €.`,`Fee €${fee} exceeds your transfer budget of €${ctx.budget}.`,"INSUFFICIENT_BUDGET");number("weekly_wage",0,1e9,false,false,0);const contract=day("contract_until",true);if(date&&contract&&contract<date)add("contract_until",`Darf nicht vor dem Transferdatum ${date} enden.`,`Cannot end before the transfer date ${date}.`,"INVALID_TRANSFER");if(direction==="career")text("league",100,true,b.league||"League");text("notes",2000,false);void kind;
 }else if(action==="trophy"){text("name");choice("kind",["team","individual"]);day("award_date");text("season_id",36);text("notes",2000,false);}
 return issues;
}
export function validateFootballInput(action:string,b:Record<string,any>,ctx:FootballValidationContext={}){const issues=footballValidationIssues(action,b,ctx);if(issues.length)throw new FootballValidationError(issues);}
