import type {FootballMatch} from "./football";
import {buildFootballMediaContext,footballMediaPlan,footballMediaVersion,footballMediaSeed,type FootballMediaPlan} from "./football-media-context";

export function editorialFootball(m:FootballMatch,p:any,history:FootballMatch[],language:string,recent:{outlet?:string|null;headline?:string;body?:string}[]=[]){
 const en=language==="en",c=buildFootballMediaContext(m,p,history),s=m.player_stats,played=p.mode==="player"&&s?.appearance==="played"&&c.result!==null,bench=p.mode==="player"&&!played&&c.result!==null;
 const oldHeadlines=new Set(recent.map(x=>x.headline)),seed=c.seed+footballMediaSeed(recent.map(x=>x.headline||"").join("|")),choose=(de:string[],english:string[],offset=0)=>{const all=en?english:de,fresh=all.filter(text=>!oldHeadlines.has(text)),choices=fresh.length?fresh:all;return choices[(seed+offset)%choices.length];},club=m.tracked_club,name=p.person_name;
 const score=`${m.home_club} ${m.home_score} – ${m.away_score} ${m.away_club}${m.home_penalties==null?"":` (${m.home_penalties}:${m.away_penalties} ${en?"on penalties":"i. E."})`}`;
 const outcome=c.result==="W"?(en?"win":"Sieg"):c.result==="L"?(en?"defeat":"Niederlage"):(en?"draw":"Unentschieden");
 const performance=played?(en?`${name} contributed ${s!.goals} goals and ${s!.assists} assists${s!.minutes==null?"":` in ${s!.minutes} minutes`}${s!.rating==null?"":`, with a ${Number(s!.rating).toFixed(1)} match rating`}.`:`${name} steuerte ${s!.goals} Tore und ${s!.assists} Assists bei${s!.minutes==null?"":` in ${s!.minutes} Minuten`}${s!.rating==null?"":` und erhielt ein Matchrating von ${Number(s!.rating).toFixed(1)}`}.`):bench?(en?`${name} did not play. There is no individual performance to rate.`:`${name} kam nicht zum Einsatz. Eine individuelle Leistungsbewertung wäre deshalb fehl am Platz.`):(en?`${club}'s result is assessed from the team's score and the available team data.`:`Für ${club} zählt das Teamergebnis; die verfügbaren Mannschaftswerte liefern die weitere Einordnung.`);
 const season=played?(en?`${name}'s season totals are ${c.summary.goals} goals and ${c.summary.assists} assists in ${c.summary.appearances} appearances.`:`${name} steht in dieser Saison nach ${c.summary.appearances} eingetragenen Einsätzen bei ${c.summary.goals} Toren und ${c.summary.assists} Assists.`):(en?`The season balance is ${c.summary.wins} wins, ${c.summary.draws} draws and ${c.summary.losses} defeats.`:`Die Saisonbilanz: ${c.summary.wins} Siege, ${c.summary.draws} Remis und ${c.summary.losses} Niederlagen.`);
 const stats=[m.possession!=null?`${m.possession}% ${en?"possession":"Ballbesitz"}`:null,m.shots!=null?`${m.shots} ${en?"shots":"Schüsse"}`:null,m.shots_on_target!=null?`${m.shots_on_target} ${en?"on target":"aufs Tor"}`:null,m.xg!=null?`${m.xg} xG`:null].filter(Boolean).join(" · ");
 const form=c.previousResults.length?(en?`Before this match, the previous ${c.previousResults.length} results included ${c.previousResults.filter(x=>x.result==="W").length} wins. This ${outcome} adds a new reference point.`:`Vor dieser Partie brachte ${club} aus den letzten ${c.previousResults.length} Spielen ${c.previousResults.filter(x=>x.result==="W").length} Siege mit. Das heutige ${c.ownScore}:${c.opponentScore} ergänzt dieses Formbild.`):season;
 const critique=bench?(en?"The player's next appearance will provide the basis for a sporting judgment; this result belongs to the team.":"Für ein sportliches Urteil über den Spieler braucht es den nächsten Einsatz; dieses Ergebnis gehört der Mannschaft."):Number(c.opponentScore)>0?(en?`${club} conceded ${c.opponentScore} goals. Even in a ${outcome}, that is a concrete detail to examine rather than a reason to invent tactical mistakes.`:`${club} ließ ${c.opponentScore} Gegentore zu. Auch bei einem ${outcome} bleibt das ein konkreter Ansatzpunkt für die nächste Bewertung.`):(en?`${club} kept the opposition score at zero. The next test is whether the team can repeat that result.`:`${club} hielt den Gegner bei null Toren. Der nächste Prüfstein ist, ob die Mannschaft dieses Ergebnis wiederholen kann.`);
 const contribution=played?`${s!.goals+s!.assists} ${en?"direct goal contributions":"direkte Torbeteiligungen"}`:outcome;
 const headlineBase=played&&s!.goals>=3?(en?`${name} scores a hat-trick`:`Dreierpack für ${name}`):played&&s!.goals>=2?(en?`Two goals for ${name}`:`Doppelpack für ${name}`):bench?(en?`${name} without an appearance`:`${name} ohne Einsatz`):`${club}: ${outcome}`;
 const plan=footballMediaPlan(c,recent);
 function report(row:FootballMediaPlan,i:number){let headline="",body="";
  switch(row.kind){
   case "recap":headline=choose([headlineBase,`${club} gegen ${c.opponent}: ${c.ownScore}:${c.opponentScore} in ${m.competition}`,`${m.competition}: ${outcome} für ${club}`],[headlineBase,`${club} vs ${c.opponent}: ${c.ownScore}:${c.opponentScore} in ${m.competition}`,`${m.competition}: ${outcome} for ${club}`]);body=`${score}. ${choose([`Der ${outcome} gegen ${c.opponent} gibt diesem Auftritt in ${m.competition} seine Richtung.`,`Für ${club} endet die Partie in ${m.competition} mit einem ${outcome}.`,`Das ${c.ownScore}:${c.opponentScore} gegen ${c.opponent} ist das Ergebnis, an dem dieser Auftritt gemessen wird.`],[`The ${outcome} against ${c.opponent} defines this outing in ${m.competition}.`,`${club} finish this ${m.competition} match with a ${outcome}.`,`The ${c.ownScore}:${c.opponentScore} against ${c.opponent} is the result that defines this performance.`],i)} ${performance}${m.notes?` ${m.notes}`:""}`;break;
   case "broadcast":headline=choose([`Im TV-Blick: ${contribution}`,`Was von ${club} hängen bleibt`,`${outcome} mit klaren Zahlen`],[`The TV view: ${contribution}`,`What stands out for ${club}`,`A ${outcome} with clear numbers`],i);body=`${choose([`Der erste Blick fällt auf das ${c.ownScore}:${c.opponentScore}, der zweite auf den individuellen Anteil.`,`Das Ergebnis gegen ${c.opponent} setzt den Rahmen für die TV-Analyse.`,`In ${m.competition} liefert dieser Auftritt mehr als nur einen Endstand.`],[`The first look is at the ${c.ownScore}:${c.opponentScore}; the second is at the individual impact.`,`The result against ${c.opponent} sets the frame for the broadcast analysis.`,`This ${m.competition} appearance offers more than a final score.`],i)} ${performance}`;break;
   case "analysis":headline=choose([`${club}: die Statistik zum ${outcome}`,`Zahlencheck nach ${m.competition}`,`Worauf das ${c.ownScore}:${c.opponentScore} den Blick lenkt`],[`${club}: the numbers behind the ${outcome}`,`The ${m.competition} numbers check`,`What the ${c.ownScore}:${c.opponentScore} brings into focus`],i);body=stats?`${stats}. ${en?`These are ${club}'s available team statistics. Read alongside the ${c.ownScore}:${c.opponentScore} result, they provide a basis for assessment; they do not establish how individual goals were created.`:`Das sind die verfügbaren Teamwerte von ${club}. Zusammen mit dem ${c.ownScore}:${c.opponentScore} liefern sie eine Basis für die Bewertung; einzelne Torabläufe lassen sich daraus nicht ableiten.`}`:`${form} ${performance}`;break;
   case "local":headline=choose([`${club} zwischen Ergebnis und Erwartung`,`${outcome}: der Vereinsblick`,`${c.ownScore}:${c.opponentScore} und die Frage nach dem nächsten Schritt`],[`${club}: result meets expectation`,`${outcome}: the club perspective`,`${c.ownScore}:${c.opponentScore} and the next step`],i);body=`${form} ${en?`${club}'s immediate story is the ${outcome} against ${c.opponent}, in ${m.competition}. The next match will show whether this becomes a trend.`:`Für ${club} steht zunächst der ${outcome} gegen ${c.opponent} in ${m.competition}. Ob daraus eine Entwicklung wird, zeigt erst das nächste Spiel.`}`;break;
   case "international":headline=choose([`${c.opponent} im Blick nach dem ${m.home_score}:${m.away_score}`,`${m.competition}: ein Ergebnis aus zwei Perspektiven`,`${club} und ${c.opponent}: die internationale Einordnung`],[`${c.opponent} in focus after the ${m.home_score}:${m.away_score}`,`${m.competition}: one result, two perspectives`,`${club} and ${c.opponent}: the outside view`],i);body=`${score}. ${en?`For an outside observer, the competition and both clubs matter: ${m.competition} gives this meeting its context. ${club}'s ${outcome} is also part of ${c.opponent}'s story; only the recorded result and supplied statistics support this assessment.`:`Aus der Außenperspektive gehören Wettbewerb und beide Vereine zusammen: ${m.competition} bildet den Rahmen dieser Begegnung. Der ${outcome} von ${club} ist zugleich ein Teil der Geschichte von ${c.opponent}; für die Einordnung zählen das Ergebnis und die verfügbaren Werte.`}`;break;
   case "statistics":headline=choose([`${played?name:club}: der Saisonstand nach diesem Spiel`,`${contribution} im Zahlenvergleich`,`${outcome} trifft auf die Saisonbilanz`],[`${played?name:club}: the updated season figures`,`${contribution} in context`,`The ${outcome} meets the season balance`],i);body=`${season} ${played?(en?`This match accounts for ${s!.goals} of those goals and ${s!.assists} of those assists. The figures track a season, rather than predicting what happens next.`:`Auf diese Partie entfallen ${s!.goals} dieser Tore und ${s!.assists} dieser Assists. Die Zahlen beschreiben die Saison und nehmen das nächste Spiel nicht vorweg.`):`${c.summary.goalsFor}:${c.summary.goalsAgainst} ${en?"team goals across the season":"Mannschaftstore über die Saison"}.`}`;break;
   case "critical":headline=choose([`Nach dem ${outcome}: der zweite Blick`,`Was das Ergebnis offenlässt`,`${club}: Lob und Prüfauftrag`],[`After the ${outcome}: a second look`,`What the result leaves open`,`${club}: credit and questions`],i);body=`${critique} ${played&&s!.rating!=null?(en?`${name}'s ${Number(s!.rating).toFixed(1)} rating is one piece of that assessment.`:`Das Matchrating von ${name} (${Number(s!.rating).toFixed(1)}) ist ein Teil dieser Einordnung.`):form}`;break;
   case "fan":headline=choose([`Kurvenstimme zum ${c.ownScore}:${c.opponentScore}`,`${club}, das bleibt im Kopf`,`${m.competition}: mein erster Gedanke`],[`From the stands: ${c.ownScore}:${c.opponentScore}`,`${club}, this sticks in the mind`,`${m.competition}: my first thought`],i);body=c.result==="W"?choose([`${c.ownScore}:${c.opponentScore} gegen ${c.opponent}! So darf es für ${club} weitergehen.`,`${club} gewinnt, und ${contribution} sprechen heute für sich.`,`Dieser ${outcome} in ${m.competition} macht Lust auf das nächste Spiel.`],[`${c.ownScore}:${c.opponentScore} against ${c.opponent}! More of that for ${club}, please.`,`${club} win, and ${contribution} speak for themselves today.`,`This ${m.competition} win makes me want the next match already.`],i):choose([`${c.ownScore}:${c.opponentScore} gegen ${c.opponent}. Das muss ich erstmal einordnen.`,`Ein ${outcome} in ${m.competition} — jetzt zählt, wie ${club} darauf reagiert.`,`${club} bleibt mein Verein. Das Ergebnis heute wirft trotzdem Fragen auf.`],[`${c.ownScore}:${c.opponentScore} against ${c.opponent}. I need a moment with that one.`,`A ${outcome} in ${m.competition} — now let's see how ${club} respond.`,`${club} are still my club. Today's result still leaves questions.`],i);break;
   case "social":headline=choose([`${m.competition} in einem Satz`,`${played?name:club}: heute im Fokus`,`Abpfiff. Zahlen. Einordnung.`],[`${m.competition} in one sentence`,`${played?name:club}: today's focus`,`Whistle. Numbers. Perspective.`],i);body=played?choose([`${name}: ${contribution}. ${club} beendet das Spiel gegen ${c.opponent} mit ${c.ownScore}:${c.opponentScore}.`,`${s!.goals} Tore, ${s!.assists} Assists für ${name}. Das ist der individuelle Zahlenstand nach ${m.competition}.`,`${club} gegen ${c.opponent}: ${c.ownScore}:${c.opponentScore}. ${name} liefert ${contribution}.`],[`${name}: ${contribution}. ${club} finish against ${c.opponent} at ${c.ownScore}:${c.opponentScore}.`,`${s!.goals} goals, ${s!.assists} assists for ${name}. Today's individual ${m.competition} numbers.`,`${club} vs ${c.opponent}: ${c.ownScore}:${c.opponentScore}. ${name} provides ${contribution}.`],i):`${score}. ${choose([`Der Rest ist die nächste Geschichte.`,`${outcome} in ${m.competition}.`,`Ein Ergebnis, zwei Vereinsblicke.`],[`The rest is the next story.`,`${outcome} in ${m.competition}.`,`One result, two club perspectives.`],i)}`;break;
  }
  return {kind:row.kind,author:row.author,outlet:row.outlet?.name||null,headline,body,source:"editorial" as const,generation_version:footballMediaVersion,model:null};
 }
 const items=plan.map(report),question=bench?choose(["Wie bereitest du dich auf die nächste Einsatzchance vor?","Was nimmst du aus der Partie ohne eigenen Einsatz mit?"],["How are you preparing for your next opportunity?","What do you take from watching this match without playing?"]):played?choose([`Wie ordnest du deine ${s!.goals+s!.assists} Torbeteiligungen bei diesem ${c.ownScore}:${c.opponentScore} ein?`,`Was bedeutet dieser ${outcome} in ${m.competition} für deine Entwicklung?`],[`How do you assess your ${s!.goals+s!.assists} direct goal contributions in this ${c.ownScore}:${c.opponentScore}?`,`What does this ${m.competition} ${outcome} mean for your development?`]):choose([`Was nimmst du aus dem ${c.ownScore}:${c.opponentScore} gegen ${c.opponent} mit?`,`Wie passt dieser ${outcome} zum bisherigen Saisonverlauf?`],[`What do you take from the ${c.ownScore}:${c.opponentScore} against ${c.opponent}?`,`How does this ${outcome} fit the season so far?`]);
 return {items,interview:{question,options:en?["We need to carry the positives into the next match.","The result matters, but we still have details to improve.","Our focus is on the team's next step."]:["Wir müssen die guten Ansätze ins nächste Spiel mitnehmen.","Das Ergebnis zählt, aber bei den Details können wir noch besser werden.","Unser Fokus liegt auf dem nächsten Schritt als Mannschaft."]}};
}
