import {NextResponse} from "next/server";
import {uiLanguage} from "@/lib/ui-language";
import {InputError} from "@/lib/game-input";
const messages:Record<string,[string,string]>={
 CONTRACT_ALREADY_RECORDED:["Für dieses Team wurde an diesem Karrieredatum bereits ein Vertrag abgeschlossen oder abgelehnt.","A contract for this team has already been signed or declined on this career date."],
 CONTRACT_CONFLICT:["In dieser Kategorie läuft bereits ein Vertrag mit überlappender Laufzeit.","An overlapping contract is already active in this category."],
 UNAUTHORIZED:["Bitte melde dich erneut an.","Please sign in again."],FORBIDDEN:["Du hast keinen Zugriff auf diese Karriere.","You do not have access to this career."],INVALID_DRAFT:["Bitte Draftstatus und eine gültige Draftposition wählen.","Choose a draft status and valid draft position."],INVALID_ROOKIE_SEASON:["Die Rookie-Saison darf nicht nach der aktiven Saison liegen.","The rookie season cannot be after the active season."],NO_UNIVERSE:["Wähle zuerst eine Karriere aus.","Select a career first."],NO_CAREER:["Die Spielerakte fehlt.","The player file is missing."],DATABASE_UNAVAILABLE:["Die Datenbank ist gerade nicht erreichbar.","The database is currently unavailable."],
 INVALID_DATE:["Bitte ein gültiges Datum angeben.","Enter a valid date."],INVALID_ID:["Der gewählte Eintrag ist ungültig.","The selected item is invalid."],INVALID_VALUES:["Bitte gültige Zahlen eintragen. Zähler dürfen nicht negativ sein.","Enter valid numbers. Counts cannot be negative."],MISSING_VALUES:["Bitte alle fehlenden Spielwerte prüfen und ergänzen.","Review and complete all missing game values."],INVALID_SCORE:["Der Endstand benötigt zwei unterschiedliche, nicht negative Punktzahlen.","A final score needs two different, nonnegative scores."],INVALID_SHOOTING:["Getroffene Würfe und Versuche passen nicht zusammen.","Made shots and attempts are inconsistent."],POINTS_MISMATCH:["PTS muss zu den Würfen passen: 2 × FGM + 3PM + FTM.","PTS must match the shots: 2 × FGM + 3PM + FTM."],INVALID_POINTS:["Die Spielerpunkte überschreiten die Team-Punktzahl.","Player points exceed the team score."],INVALID_STATUS:["Bitte einen gültigen Einsatzstatus wählen.","Choose a valid appearance status."],TEXT_TOO_LONG:["Der Text ist zu lang. Bitte kürzen.","The text is too long. Please shorten it."],INVALID_NOTABLES:["Notizen bitte als Spieler | Team | Beschreibung eintragen.","Enter notables as Player | Team | Description."],
 STALE_GAME:["Dieses Spiel wurde bereits gespeichert oder geändert. Lade die Seite neu, bevor du korrigierst.","This game has already been saved or changed. Reload before editing."],GAME_NOT_FOUND:["Dieses Spiel ist nicht verfügbar.","This game is unavailable."],TEAM_NOT_IN_GAME:["Dein damaliges Team spielt in dieser Partie nicht mit.","Your team at that date is not in this game."],INVALID_TEAM:["Bitte ein anderes aktives Team wählen.","Choose a different active team."],TRADE_IN_PAST:["Ein Teamwechsel kann nicht vor dem aktuellen Karrieredatum liegen.","A team change cannot precede the current career date."],STALE_OFFER:["Dieses Angebot ist nicht mehr aktuell.","This offer is no longer current."],INTERVIEW_CLOSED:["Diese Pressefrage wurde bereits beantwortet.","This question has already been answered."],INVALID_ANSWER:["Diese Antwort ist nicht verfügbar.","This answer is unavailable."],ACTION_RUNNING:["Diese Aktion läuft bereits. Bitte kurz warten.","This action is already running. Please wait."],RATE_LIMITED:["Zu viele Anfragen. Bitte in einer Minute erneut versuchen.","Too many requests. Try again in a minute."],DAILY_RESPONSE:["Du hast heute bereits Stellung bezogen.","You have already responded today."],BODY_TOO_LARGE:["Die übertragenen Daten sind zu groß.","The submitted data is too large."],INVALID_JSON:["Die Anfrage konnte nicht gelesen werden.","The request could not be read."],AI_UNAVAILABLE:["Die KI-Berichterstattung ist noch nicht eingerichtet.","AI coverage has not been configured yet."],SCAN_FAILED:["Die Bildwerte sind nicht zuverlässig lesbar. Bitte zuschneiden oder manuell ergänzen.","The image values could not be read reliably. Crop the image or enter them manually."]
};
export async function apiFailure(error:unknown){
 const lang=await uiLanguage().catch(()=>"de"),en=lang==="en";
 const code=error instanceof Error?error.message:typeof error==="object"&&error&&"message" in error?String(error.message):"";
 let status=error instanceof InputError?400:500;
 if(code==="UNAUTHORIZED")status=401;else if(code==="FORBIDDEN")status=403;else if(code==="GAME_NOT_FOUND")status=404;
 else if(["STALE_GAME","STALE_OFFER","INTERVIEW_CLOSED","ACTION_RUNNING","DAILY_RESPONSE","NO_UNIVERSE","NO_CAREER","CONTRACT_CONFLICT","CONTRACT_ALREADY_RECORDED"].includes(code))status=409;
 else if(code==="RATE_LIMITED")status=429;else if(code==="BODY_TOO_LARGE")status=413;else if(code.startsWith("INVALID_")||code==="TEAM_NOT_IN_GAME"||code==="TRADE_IN_PAST")status=400;
 const pair=messages[code];if(!pair)console.error("Career request failed",{code:typeof error==="object"&&error&&"code" in error?error.code:code});
 return NextResponse.json({error:pair?pair[en?1:0]:(en?"The action could not be completed. Your saved career remains available.":"Die Aktion konnte nicht abgeschlossen werden. Deine gespeicherte Karriere bleibt verfügbar."),code:pair?code:"REQUEST_FAILED"},{status,headers:{"Cache-Control":"no-store"}});
}
export async function readJson(req:Request,maxBytes=128_000):Promise<any>{
 const reader=req.body?.getReader();if(!reader)throw new InputError("INVALID_JSON");let size=0;const chunks:Uint8Array[]=[];
 while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new InputError("BODY_TOO_LARGE");}chunks.push(value);}
 try{const value=JSON.parse(Buffer.concat(chunks).toString("utf8"));if(!value||typeof value!=="object"||Array.isArray(value))throw Error();return value;}catch{throw new InputError("INVALID_JSON");}
}
