import Link from "next/link";
import {coopContext,coopPlayers,coopStats} from "@/lib/coop-data";
import {checked} from "@/lib/data";
import {summarizeStats,summarizeCareerMarks} from "@/lib/stats";
import {sharedMatchups} from "@/lib/coop";
import {draftLabel} from "@/lib/career-background";
import {localDate} from "@/lib/format";
import {label} from "@/lib/labels";
import {PageHeader,Section,EmptyState} from "@/components/Editorial";
import {CoopSetup,CoopScoreForm,CoopProposalButtons} from "@/components/CoopControls";
import TeamBadge from "@/components/TeamBadge";
import MediaCard from "@/components/MediaCard";
export const dynamic="force-dynamic";

export default async function Page({searchParams}:{searchParams:Promise<{season?:string;page?:string}>}) {
 const context=await coopContext(),{link,universe,client}=context,lang=universe.language==="en"?"en":"de",en=lang==="en";
 if(!link?.guest_universe_id)return <><PageHeader title={en?"Co-op":"Koop"} subtitle={en?"Two players. One MyNBA world.":"Zwei Spieler. Eine MyNBA-Welt."}/><CoopSetup link={link} language={lang}/></>;
 const players=await coopPlayers(context),host=players.find(p=>p.universe_id===link.host_universe_id),guest=players.find(p=>p.universe_id===link.guest_universe_id);
 if(!host||!guest)throw Error("COOP_NOT_LINKED");
 const query=await searchParams,seasons=checked(await client.from("seasons").select("id,label,start_date").order("start_date",{ascending:false}))||[];
 const selected=seasons.find(s=>s.id===query.season)||seasons.find(s=>s.id===universe.current_season_id)||seasons[0];
 if(!selected)return <EmptyState title={en?"No season available":"Keine Saison vorhanden"}/>;
 const ids=[host.id,guest.id],page=Math.max(1,Math.min(10000,Math.floor(Number(query.page)||1)));
 const [stats,feed,trophies,results,proposals]=await Promise.all([
  coopStats(context,ids,selected.id),
  client.from("media_posts").select("*",{count:"exact"}).in("career_id",ids).eq("language",lang).order("created_at",{ascending:false}).order("id").range((page-1)*20,page*20-1),
  client.from("trophies").select("id,career_id,title,awarded_on").in("career_id",ids).eq("season_id",selected.id).eq("language",lang).order("awarded_on",{ascending:false}).limit(200).then(checked),
  client.from("universe_games").select("game_id,universe_id,home_score,away_score,games!inner(season_id)").in("universe_id",[host.universe_id,guest.universe_id]).eq("games.season_id",selected.id).limit(1000).then(checked),
  client.from("coop_score_proposals").select("id,requested_by,host_game_id,guest_game_id,home_score,away_score,status,created_at").eq("link_id",link.id).eq("status","pending").order("created_at").limit(100).then(checked)
 ]);
 const proposalGames=proposals?.length?checked(await client.from("games").select("id,game_day,home:teams!games_home_team_id_fkey(abbreviation),away:teams!games_away_team_id_fkey(abbreviation)").in("id",[...new Set(proposals.map(p=>p.host_game_id))]))||[]:[];
 const posts=checked(feed)||[],byCareer=(id:string)=>stats.filter(s=>s.career_id===id),hostStats=byCareer(host.id),guestStats=byCareer(guest.id),a=summarizeStats(hostStats),b=summarizeStats(guestStats),ma=summarizeCareerMarks(hostStats),mb=summarizeCareerMarks(guestStats),matches=sharedMatchups(hostStats,guestStats);
 const resultFor=(u:string,g:string)=>(results||[]).find(r=>r.universe_id===u&&r.game_id===g);
 const metrics:[string,number,number,boolean?][]=[[en?"Appearances":"Einsätze",a.games,b.games],["PPG",a.ppg,b.ppg,true],["RPG",a.rpg,b.rpg,true],["APG",a.apg,b.apg,true],["SPG",a.spg,b.spg,true],["BPG",a.bpg,b.bpg,true],["FG%",a.fg*100,b.fg*100,true],["3P%",a.tp*100,b.tp*100,true],[en?"Season high · PTS":"Saisonbestwert · PTS",ma.careerHighPoints,mb.careerHighPoints],["Double-Doubles",ma.doubleDoubles,mb.doubleDoubles],["Triple-Doubles",ma.tripleDoubles,mb.tripleDoubles],[en?"50+ point games":"50+ Punkte-Spiele",ma.games50Plus,mb.games50Plus]];
 return <>
  <PageHeader title={link.name} section={en?"Co-op":"Koop"} subtitle={en?"Your shared MyNBA save. Each player controls their own career.":"Euer gemeinsamer MyNBA-Spielstand. Jeder steuert seine eigene Karriere."}/>
  <nav className="sectionNav" aria-label={en?"Co-op sections":"Koop-Bereiche"}>{[["comparison",en?"Comparison":"Vergleich"],["matchups",en?"Shared games":"Gemeinsame Spiele"],["feed",en?"Shared media":"Gemeinsame Medien"],["connection",en?"Connection":"Verbindung"]].map(([id,text])=><a key={id} href={"#"+id}>{text}</a>)}</nav>
  <div className="coopPlayers">{[host,guest].map(p=><article key={p.id}><TeamBadge team={p.current_team}/><div><h2>{p.player_name}</h2><p>{p.current_team?.abbreviation} · {p.position} · OVR {p.overall}</p><p className="muted">{draftLabel(p,lang)}</p><small>{en?"Career date":"Karrieredatum"}: {localDate(p.universe_date,lang)}</small></div></article>)}</div>
  {host.universes.current_season_id!==guest.universes.current_season_id&&<p className="coopNotice">{en?"You are currently in different seasons. The comparison below always uses the same selected season for both players.":"Ihr seid gerade in unterschiedlichen Saisons. Der Vergleich unten verwendet für beide Spieler dieselbe ausgewählte Saison."}</p>}
  <Section id="comparison" title={en?"Side by side":"Im direkten Vergleich"}>
   <form method="get" className="coopSeason"><label>{en?"Season":"Saison"}<select name="season" defaultValue={selected.id}>{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><button>{en?"Compare":"Vergleichen"}</button></form>
   <p className="muted">{en?"Per-game averages include appearances only. Missed games remain visible in the individual game logs. The media feed below covers all seasons.":"Durchschnitte zählen nur tatsächliche Einsätze. Spiele ohne Einsatz bleiben in den einzelnen Spielverläufen sichtbar. Der Medienfeed unten umfasst alle Saisons."}</p>
   <div className="tableWrap"><table className="coopComparison"><thead><tr><th scope="col">{selected.label}</th><th scope="col">{host.player_name}</th><th scope="col">{guest.player_name}</th></tr></thead><tbody>{metrics.map(([title,x,y,decimal])=><tr key={title}><th scope="row">{title}</th><td>{!a.games&&title!==(en?"Appearances":"Einsätze")?"—":decimal?x.toFixed(1):x}</td><td>{!b.games&&title!==(en?"Appearances":"Einsätze")?"—":decimal?y.toFixed(1):y}</td></tr>)}</tbody></table></div>
   <div className="grid2">{[host,guest].map(p=><div key={p.id}><h3>{p.player_name} · {en?"Achievements":"Erfolge"}</h3>{trophies?.some(t=>t.career_id===p.id)?<ul>{trophies.filter(t=>t.career_id===p.id).map(t=><li key={t.id}>{t.title} · {localDate(t.awarded_on,lang)}</li>)}</ul>:<p className="muted">{en?"No confirmed titles this season.":"Noch keine bestätigten Titel in dieser Saison."}</p>}</div>)}</div>
  </Section>
  {!!proposals?.length&&<Section title={en?"Confirm result corrections":"Endstandkorrekturen bestätigen"}>{proposals.map(p=><article className="coopMatch" key={p.id}><p>{(()=>{const g=proposalGames.find(g=>g.id===p.host_game_id);return g?`${localDate(g.game_day,lang)} · ${g.away?.abbreviation} @ ${g.home?.abbreviation}`:""})()}</p><h3>{en?"Proposed final score":"Vorgeschlagener Endstand"}: {p.away_score} – {p.home_score}</h3><p>{en?"Away – home. Check the matchup and confirm only if it matches your MyNBA save.":"Auswärts – Heim. Prüfe die Partie und bestätige nur, wenn das Ergebnis zu eurem MyNBA-Spielstand passt."}</p><Link href={"/game/"+(universe.id===host.universe_id?p.host_game_id:p.guest_game_id)}>{en?"Open your game":"Dein Spiel öffnen"} ↗</Link><CoopProposalButtons language={lang} id={p.id} own={p.requested_by===universe.id}/></article>)}</Section>}
  <Section id="matchups" title={en?"The same court":"Auf demselben Court"}>
   {!matches.length?<EmptyState title={en?"Your first shared game is still ahead":"Euer erstes gemeinsames Spiel steht noch aus"} detail={en?"Once both of you enter the same matchup, both stat lines appear here. Date, home team, away team, season and stage must match.":"Sobald ihr beide dieselbe Partie eintragt, stehen hier beide Statlines. Datum, Heimteam, Auswärtsteam, Saison und Phase müssen übereinstimmen."}/>:matches.map(m=>{const g=m.host.games,r=resultFor(host.universe_id,g.id);return <article key={g.id} id={"match-"+g.id} className="coopMatch"><div className="coopMatchHeading"><div><small>{localDate(g.game_day,lang)} · {label(g.stage,lang)}</small><h3>{g.away?.abbreviation} @ {g.home?.abbreviation}</h3><p>{m.sameTeam?(en?"Together on the same team":"Gemeinsam im selben Team"):(en?"Head to head":"Im direkten Duell")}</p></div><strong className="coopScore">{r?.away_score??"—"} : {r?.home_score??"—"}</strong></div><div className="grid2">{[[host,m.host],[guest,m.guest]].map(([p,s])=><div key={p.id}><h4>{p.player_name}</h4><p className="coopStatline">{s.appearance_status==="played"?`${s.points} PTS · ${s.rebounds} REB · ${s.assists} AST`:label(s.appearance_status,lang)}</p><p className="muted">{s.appearance_status==="played"?`${s.steals} STL · ${s.blocks} BLK · ${s.turnovers} TO · ${s.fgm}/${s.fga} FG`:""}</p>{p.universe_id===universe.id&&<Link href={"/game/"+s.game_id}>{en?"Your game entry":"Dein Spieleintrag"} ↗</Link>}</div>)}</div>{r&&<CoopScoreForm language={lang} hostGameId={g.id} guestGameId={m.guest.game_id} home={g.home?.abbreviation||"Home"} away={g.away?.abbreviation||"Away"} homeScore={r.home_score||0} awayScore={r.away_score||0}/>}</article>})}
  </Section>
  <Section title={en?"Latest entries":"Zuletzt eingetragen"}><div className="grid2">{[host,guest].map(p=><div key={p.id}><h3>{p.player_name}</h3>{byCareer(p.id).sort((x,y)=>y.games.game_day.localeCompare(x.games.game_day)).slice(0,5).map(s=>{const r=resultFor(p.universe_id,s.game_id);return <article className="railStory" key={s.id}><strong>{s.games.away?.abbreviation} @ {s.games.home?.abbreviation} · {r?.away_score??"—"}:{r?.home_score??"—"}</strong><p>{localDate(s.games.game_day,lang)} · {s.appearance_status==="played"?`${s.points} PTS · ${s.rebounds} REB · ${s.assists} AST`:label(s.appearance_status,lang)}</p></article>})}{!byCareer(p.id).length&&<p className="muted">{en?"No games recorded this season.":"Noch keine Spiele in dieser Saison eingetragen."}</p>}</div>)}</div></Section>
  <Section id="feed" title={en?"One world, both stories":"Eine Welt, beide Geschichten"}>
   {posts.length?<div className="mediaStack">{posts.map(p=><div className="coopMedia" key={p.id}><p className="coopAttribution">{players.find(c=>c.id===p.career_id)?.player_name}</p><MediaCard post={p} gameHref={p.career_id===context.career.id?undefined:null}/></div>)}</div>:<EmptyState title={en?"Your shared newsroom is ready":"Eure gemeinsame Redaktion ist bereit"} detail={en?"News and social reactions from both careers appear here automatically when either player generates coverage in this language.":"News und Social-Reaktionen beider Karrieren erscheinen hier automatisch, sobald einer von euch Berichte in dieser Sprache erzeugt."}/>}
   <nav className="pagination" aria-label={en?"Media archive":"Medienarchiv"}>{page>1&&<Link href={`/coop?season=${selected.id}&page=${page-1}#feed`}>← {en?"Newer":"Neuere"}</Link>}<span>{en?"Page":"Seite"} {page}</span>{page*20<(feed.count||0)&&<Link href={`/coop?season=${selected.id}&page=${page+1}#feed`}>{en?"Older":"Ältere"} →</Link>}</nav>
  </Section>
  <Section id="connection" title={en?"Your connection":"Eure Verbindung"}><p>{en?"Each account edits only its own player. Shared access covers profiles, statistics, achievements, final scores and media. Salaries, contracts, private notes and account data stay outside this area.":"Jeder Account bearbeitet nur seinen Spieler. Ihr teilt Profile, Statistiken, Erfolge, Endstände und Medien. Gehälter, Verträge, private Notizen und Accountdaten bleiben außerhalb dieses Bereichs."}</p><CoopSetup link={link} language={lang}/></Section>
 </>;
}
